package view;

   

 public class Account extends javax.swing.JFrame {

   

    /** Preferred constructor with user context */



    public Account ()  {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerpanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Username_Text_Field = new javax.swing.JTextField();
        Pencil_label = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        update_password_Text_Field = new javax.swing.JTextField();
        Copy_Button = new javax.swing.JButton();
        UserID_Text_Field = new javax.swing.JTextField();
        ID_Label = new javax.swing.JLabel();
        topPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Library_Button1 = new javax.swing.JButton();
        Library_Button2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Save_Button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().setLayout(null);

        centerpanel.setBackground(new java.awt.Color(255, 255, 255));
        centerpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        centerpanel.setLayout(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        centerpanel.add(jPanel5);
        jPanel5.setBounds(120, 230, 0, 0);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        centerpanel.add(jPanel8);
        jPanel8.setBounds(310, 230, 0, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (39).png"))); // NOI18N
        centerpanel.add(jLabel1);
        jLabel1.setBounds(20, 10, 110, 100);

        Username_Text_Field.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Username_Text_Field.setBorder(null);
        Username_Text_Field.addActionListener(this::Username_Text_FieldActionPerformed);
        centerpanel.add(Username_Text_Field);
        Username_Text_Field.setBounds(130, 40, 140, 40);

        Pencil_label.setBackground(new java.awt.Color(254, 254, 254));
        Pencil_label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Pencil_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-17 205936.png"))); // NOI18N
        Pencil_label.setText("Edit the profile");
        centerpanel.add(Pencil_label);
        Pencil_label.setBounds(905, 20, 160, 26);

        getContentPane().add(centerpanel);
        centerpanel.setBounds(99, 140, 1080, 120);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jTextField3.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setText("Password");
        jTextField3.setBorder(null);
        jTextField3.addActionListener(this::jTextField3ActionPerformed);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(30, 30, 120, 30);

        update_password_Text_Field.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        update_password_Text_Field.setText(" Update password");
        update_password_Text_Field.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        update_password_Text_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                update_password_Text_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                update_password_Text_FieldFocusLost(evt);
            }
        });
        update_password_Text_Field.addActionListener(this::update_password_Text_FieldActionPerformed);
        jPanel1.add(update_password_Text_Field);
        update_password_Text_Field.setBounds(30, 60, 200, 50);

        Copy_Button.setBackground(new java.awt.Color(254, 254, 254));
        Copy_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-17 225511.png"))); // NOI18N
        Copy_Button.setBorder(null);
        Copy_Button.addActionListener(this::Copy_ButtonActionPerformed);
        jPanel1.add(Copy_Button);
        Copy_Button.setBounds(60, 360, 40, 30);

        UserID_Text_Field.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        UserID_Text_Field.setForeground(new java.awt.Color(153, 153, 153));
        UserID_Text_Field.setBorder(null);
        UserID_Text_Field.addActionListener(this::UserID_Text_FieldActionPerformed);
        jPanel1.add(UserID_Text_Field);
        UserID_Text_Field.setBounds(40, 360, 60, 30);

        ID_Label.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        ID_Label.setForeground(new java.awt.Color(153, 153, 153));
        ID_Label.setText("ID:");
        jPanel1.add(ID_Label);
        ID_Label.setBounds(20, 366, 20, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(100, 280, 1080, 400);

        topPanel1.setBackground(new java.awt.Color(255, 255, 255));
        topPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabel3.setBackground(new java.awt.Color(254, 254, 254));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/122.png"))); // NOI18N

        Library_Button1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        Library_Button1.setText("Home");
        Library_Button1.setBorder(null);
        Library_Button1.addActionListener(this::Library_Button1ActionPerformed);

        Library_Button2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        Library_Button2.setText("library");
        Library_Button2.setBorder(null);
        Library_Button2.addActionListener(this::Library_Button2ActionPerformed);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\bipin ranabhat\\OneDrive\\Documents\\img\\acc.png")); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout topPanel1Layout = new javax.swing.GroupLayout(topPanel1);
        topPanel1.setLayout(topPanel1Layout);
        topPanel1Layout.setHorizontalGroup(
            topPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Library_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Library_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 726, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        topPanel1Layout.setVerticalGroup(
            topPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanel1Layout.createSequentialGroup()
                .addGroup(topPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(topPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(topPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Library_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Library_Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(topPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(topPanel1);
        topPanel1.setBounds(0, 0, 1300, 70);

        Save_Button.setBackground(new java.awt.Color(0, 141, 237));
        Save_Button.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Save_Button.setForeground(new java.awt.Color(255, 255, 255));
        Save_Button.setText("Save");
        Save_Button.addActionListener(this::Save_ButtonActionPerformed);
        getContentPane().add(Save_Button);
        Save_Button.setBounds(1110, 100, 70, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Account");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 90, 120, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Save_ButtonActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void UserID_Text_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserID_Text_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserID_Text_FieldActionPerformed

    private void Copy_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Copy_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Copy_ButtonActionPerformed

    private void update_password_Text_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_password_Text_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_update_password_Text_FieldActionPerformed

    private void Username_Text_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_Text_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_Text_FieldActionPerformed

    private void update_password_Text_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_update_password_Text_FieldFocusGained
        // TODO add your handling code here:
      
    }//GEN-LAST:event_update_password_Text_FieldFocusGained

    private void update_password_Text_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_update_password_Text_FieldFocusLost
        
    }//GEN-LAST:event_update_password_Text_FieldFocusLost

    private void Library_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Library_Button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Library_Button1ActionPerformed

    private void Library_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Library_Button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Library_Button2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> new Account().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Copy_Button;
    private javax.swing.JLabel ID_Label;
    private javax.swing.JButton Library_Button1;
    private javax.swing.JButton Library_Button2;
    private javax.swing.JButton Pencil_label;
    private javax.swing.JButton Save_Button;
    private javax.swing.JTextField UserID_Text_Field;
    private javax.swing.JTextField Username_Text_Field;
    private javax.swing.JPanel centerpanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel topPanel1;
    private javax.swing.JTextField update_password_Text_Field;
    // End of variables declaration//GEN-END:variables

   

}