/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author ashishchaudhary
 */
public class cardpanel extends javax.swing.JPanel {
    

    /**
     * Creates new form
     */
    public cardpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unarchivepanel = new javax.swing.JPanel();
        filenamelbl = new javax.swing.JLabel();
        restorebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        archivepanel = new javax.swing.JPanel();
        filenamelbl1 = new javax.swing.JLabel();
        unarchivebtn1 = new javax.swing.JButton();
        deletebtn1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 255));
        setLayout(null);

        unarchivepanel.setLayout(null);

        filenamelbl.setText("nsjchdc");
        unarchivepanel.add(filenamelbl);
        filenamelbl.setBounds(40, 20, 46, 17);

        restorebtn.setText("unarchive");
        unarchivepanel.add(restorebtn);
        restorebtn.setBounds(550, 20, 86, 23);

        deletebtn.setText("delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        unarchivepanel.add(deletebtn);
        deletebtn.setBounds(650, 20, 72, 23);

        add(unarchivepanel);
        unarchivepanel.setBounds(30, 220, 760, 70);

        archivepanel.setLayout(null);

        filenamelbl1.setText("nsjchdc");
        archivepanel.add(filenamelbl1);
        filenamelbl1.setBounds(40, 20, 46, 17);

        unarchivebtn1.setText("unarchive");
        archivepanel.add(unarchivebtn1);
        unarchivebtn1.setBounds(550, 20, 86, 23);

        deletebtn1.setText("delete");
        deletebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtn1ActionPerformed(evt);
            }
        });
        archivepanel.add(deletebtn1);
        deletebtn1.setBounds(650, 20, 72, 23);

        add(archivepanel);
        archivepanel.setBounds(20, 20, 760, 70);
    }// </editor-fold>//GEN-END:initComponents

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtnActionPerformed

    private void deletebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel archivepanel;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton deletebtn1;
    private javax.swing.JLabel filenamelbl;
    private javax.swing.JLabel filenamelbl1;
    private javax.swing.JButton restorebtn;
    private javax.swing.JButton unarchivebtn1;
    private javax.swing.JPanel unarchivepanel;
    // End of variables declaration//GEN-END:variables
  public void setFileName(String fileName) {
        filenamelbl.setText(fileName);
        filenamelbl1.setText(fileName);
    }
    
    public javax.swing.JButton getRestorebtn() {
        return restorebtn;
    }
    
    public javax.swing.JButton getDeletebtn() {
        return deletebtn;
    }
    
    public javax.swing.JButton getUnarchivebtn1() {
        return unarchivebtn1;
    }
    
    public javax.swing.JButton getDeletebtn1() {
        return deletebtn1;
    }
    
    public javax.swing.JPanel getArchivepanel() {
        return archivepanel;
    }
    
    public javax.swing.JPanel getUnarchivepanel() {
        return unarchivepanel;
    }
}
