/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


/**
 *
 * @author bipin ranabhat
 */
public class CardsDeck extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CardsDeck.class.getName());

    /**
     * Creates new form CardsDeck
     */
    public CardsDeck() {
        initComponents();
         initAccountPopup(); 
        filterPopupPanel.setVisible(false);
    }
    private void initAccountPopup() {
    accountPopupMenu = new javax.swing.JPopupMenu();

    javax.swing.JMenuItem profile = new javax.swing.JMenuItem("Profile");
    javax.swing.JMenuItem logout = new javax.swing.JMenuItem("Logout");

    accountPopupMenu.add(profile);
    accountPopupMenu.add(logout);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        topPanel1 = new javax.swing.JPanel();
        Home_Button = new javax.swing.JButton();
        Logo_label = new javax.swing.JLabel();
        accountButton = new javax.swing.JButton();
        Library_Button = new javax.swing.JButton();
        filterPopupPanel = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\bipin ranabhat\\OneDrive\\Documents\\img\\left.png")); // NOI18N
        jButton1.setBorder(null);
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 100, 30, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Home / Java Language");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 100, 200, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setText("Java Language");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 150, 230, 40);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI Historic", 0, 16)); // NOI18N
        jButton4.setText("Filters");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        getContentPane().add(jButton4);
        jButton4.setBounds(1010, 563, 90, 30);

        topPanel1.setBackground(new java.awt.Color(255, 255, 255));
        topPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        topPanel1.setLayout(null);

        Home_Button.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        Home_Button.setText("Home");
        Home_Button.setBorder(null);
        Home_Button.addActionListener(this::Home_ButtonActionPerformed);
        topPanel1.add(Home_Button);
        Home_Button.setBounds(190, 20, 60, 20);

        Logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        topPanel1.add(Logo_label);
        Logo_label.setBounds(100, 10, 60, 50);

        accountButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (40).png"))); // NOI18N
        accountButton.setBorder(null);
        accountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountButtonMouseClicked(evt);
            }
        });
        accountButton.addActionListener(this::accountButtonActionPerformed);
        topPanel1.add(accountButton);
        accountButton.setBounds(1090, 10, 50, 50);

        Library_Button.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        Library_Button.setText("Library");
        Library_Button.setBorder(null);
        topPanel1.add(Library_Button);
        Library_Button.setBounds(280, 10, 70, 40);

        getContentPane().add(topPanel1);
        topPanel1.setBounds(0, 0, 1210, 70);

        filterPopupPanel.setBackground(new java.awt.Color(255, 255, 255));
        filterPopupPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        filterPopupPanel.setLayout(null);

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setText("Reset");
        jButton7.addActionListener(this::jButton7ActionPerformed);
        filterPopupPanel.add(jButton7);
        jButton7.setBounds(98, 12, 65, 23);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setText("Newest");
        filterPopupPanel.add(jTextField3);
        jTextField3.setBounds(7, 55, 156, 32);

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        jTextField4.setText("Oldest");
        filterPopupPanel.add(jTextField4);
        jTextField4.setBounds(7, 99, 156, 32);

        jButton8.setBackground(new java.awt.Color(0, 153, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Apply");
        jButton8.addActionListener(this::jButton8ActionPerformed);
        filterPopupPanel.add(jButton8);
        jButton8.setBounds(7, 149, 156, 36);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Filter by");
        filterPopupPanel.add(jLabel4);
        jLabel4.setBounds(10, 10, 60, 30);

        getContentPane().add(filterPopupPanel);
        filterPopupPanel.setBounds(900, 350, 170, 200);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(142, 142, 142));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\bipin ranabhat\\Downloads\\icon-park-outline--search.png")); // NOI18N
        jButton3.setText("Search cards");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3);
        jButton3.setBounds(110, 480, 990, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 26)); // NOI18N
        jLabel3.setText("Cards in deck = 2");

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Study cards");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(341, 341, 341))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(110, 220, 990, 220);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setText("First programmer ?");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(14, 6, 243, 36);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setText("Ada Lovelace");
        jTextField2.setBorder(null);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(20, 40, 233, 30);

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\bipin ranabhat\\Downloads\\ph--dots-three-vertical.png")); // NOI18N
        jButton5.setBorder(null);
        jPanel1.add(jButton5);
        jButton5.setBounds(959, 6, 25, 36);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Add cards");
        jButton6.addActionListener(this::jButton6ActionPerformed);
        jPanel1.add(jButton6);
        jButton6.setBounds(427, 26, 207, 36);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(110, 610, 990, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_ButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Home_ButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (filterPopupPanel.isVisible()) {
        filterPopupPanel.setVisible(false);
    } else {
        // Get the position of the Filters button on screen
        Point buttonLocation = jButton4.getLocationOnScreen();
        
        // Calculate position: just above the button, aligned to the right edge
        int x = buttonLocation.x + jButton4.getWidth() - filterPopupPanel.getWidth();
        int y = buttonLocation.y - filterPopupPanel.getHeight() - 5; // 5px gap
        
        // Set location and show the popup
        filterPopupPanel.setLocation(x, y);
        filterPopupPanel.setVisible(true);
    }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        filterPopupPanel.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jTextField3.setText("Newest");
        jTextField4.setText("Oldest");
    
        // Hide the popup
        filterPopupPanel.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void accountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountButtonActionPerformed

    private void accountButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountButtonMouseClicked
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) { // Left click only
            int x = accountButton.getWidth() - accountPopupMenu.getPreferredSize().width;
            int y = accountButton.getHeight();
            accountPopupMenu.show(accountButton, x, y);
        }
    }//GEN-LAST:event_accountButtonMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CardsDeck().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home_Button;
    private javax.swing.JButton Library_Button;
    private javax.swing.JLabel Logo_label;
    private javax.swing.JButton accountButton;
    private javax.swing.JPanel filterPopupPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel topPanel1;
    // End of variables declaration//GEN-END:variables
private javax.swing.JPopupMenu accountPopupMenu;

}
