/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import javax.swing.*;
import java.awt.event.ActionListener;

/**
 *
 * @author ashishchaudhary
 */
public class CardsPanel extends javax.swing.JPanel {

    
    public CardsPanel() {
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFlip = new javax.swing.JButton();
        lblSideIndicator = new javax.swing.JLabel();
        lblCardText = new javax.swing.JLabel();

        setLayout(null);

        btnFlip.setText("Click to Flip ");
        add(btnFlip);
        btnFlip.setBounds(70, 300, 110, 20);

        lblSideIndicator.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblSideIndicator.setText("Question ");
        add(lblSideIndicator);
        lblSideIndicator.setBounds(70, 50, 110, 20);

        lblCardText.setText("jLabel2");
        add(lblCardText);
        lblCardText.setBounds(60, 120, 290, 140);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFlip;
    private javax.swing.JLabel lblCardText;
    private javax.swing.JLabel lblSideIndicator;
    // End of variables declaration//GEN-END:variables

     public javax.swing.JLabel getLblCardText() {
        return lblCardText;
    }
    
    public javax.swing.JButton getBtnFlip() {
        return btnFlip;
    }
    
    public javax.swing.JLabel getLblSideIndicator() {
        return lblSideIndicator;
    }
    
    // Setter methods for controller
    public void setCardText(String text) {
        lblCardText.setText(text);
    }
    
    public void setSideIndicator(String text) {
        lblSideIndicator.setText(text);
    }
    
    // Add action listener for flip button
    public void addFlipButtonListener(ActionListener listener) {
        btnFlip.addActionListener(listener);
    }
}


