/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.DeckController;
import javax.swing.JOptionPane;



/**
 *
 * @author bipin ranabhat
 */
public class CreateDialog extends javax.swing.JDialog {
    private DeckController deckController;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateDialog.class.getName());

    /**
     * Creates new form CreateDialog
     */
    public CreateDialog(java.awt.Frame parent, boolean modal) {
        super(parent, "New Deck", true);  // modal
        initComponents();
        setLocationRelativeTo(parent);
    }
    
    public void setDeckController(DeckController controller) {
    this.deckController = controller;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deckNameTextField = new javax.swing.JTextField();
        createDeck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("New Deck");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("<html><b>Create your own deck.</b><font color=\"#888888\">You get the best results from<br>the cards you create yourself.</html>");

        deckNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deckNameTextField.setForeground(new java.awt.Color(153, 153, 153));
        deckNameTextField.setText("Deck name ");
        deckNameTextField.addActionListener(this::deckNameTextFieldActionPerformed);

        createDeck.setBackground(new java.awt.Color(0, 153, 255));
        createDeck.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createDeck.setForeground(new java.awt.Color(255, 255, 255));
        createDeck.setText("Create deck");
        createDeck.addActionListener(this::createDeckActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deckNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createDeck, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(deckNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createDeck, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deckNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deckNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deckNameTextFieldActionPerformed

    private void createDeckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDeckActionPerformed
        // TODO add your handling code here:
        String deckName = deckNameTextField.getText().trim();  // Replace with your JTextField name
        // Tell controller to create deck and open Deck view
        if (deckName.isEmpty() || deckName.equals("Deck name")) {
        JOptionPane.showMessageDialog(this, "Please enter a valid deck name.");
        return;
    }
    
        // Create deck and open Deck.java screen
        deckController.createDeckAndOpenDeckView(deckName);
        // Close the dialog
        dispose();
    }//GEN-LAST:event_createDeckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                CreateDialog dialog = new CreateDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createDeck;
    private javax.swing.JTextField deckNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
