/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author LENOVO
 */
public class CreateFlashcards extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateFlashcards.class.getName());

    /**
     * Creates new form CreateFlashcards
     */
    public CreateFlashcards() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel1 = new javax.swing.JPanel();
        Home_Button = new javax.swing.JButton();
        Logo_label = new javax.swing.JLabel();
        Library_Button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        centerpanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Front_Text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Back_Text = new javax.swing.JTextField();
        Home_Label = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tickButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        topPanel1.setBackground(new java.awt.Color(255, 255, 255));
        topPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Home_Button.setBackground(new java.awt.Color(254, 254, 254));
        Home_Button.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        Home_Button.setText("Home");
        Home_Button.setBorder(null);
        Home_Button.addActionListener(this::Home_ButtonActionPerformed);

        Logo_label.setBackground(new java.awt.Color(254, 254, 254));
        Logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/122.png"))); // NOI18N

        Library_Button.setBackground(new java.awt.Color(254, 254, 254));
        Library_Button.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        Library_Button.setText("Library");
        Library_Button.setBorder(null);

        jLabel4.setBackground(new java.awt.Color(254, 254, 254));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/13.png"))); // NOI18N

        javax.swing.GroupLayout topPanel1Layout = new javax.swing.GroupLayout(topPanel1);
        topPanel1.setLayout(topPanel1Layout);
        topPanel1Layout.setHorizontalGroup(
            topPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(Logo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Home_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Library_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 773, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(145, 145, 145))
        );
        topPanel1Layout.setVerticalGroup(
            topPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanel1Layout.createSequentialGroup()
                .addGroup(topPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(topPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Logo_label)
                        .addGroup(topPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(Home_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(topPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(Library_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(topPanel1);
        topPanel1.setBounds(0, 0, 1330, 70);

        centerpanel.setBackground(new java.awt.Color(255, 255, 255));
        centerpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        centerpanel.setLayout(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        centerpanel.add(jPanel5);
        jPanel5.setBounds(120, 230, 0, 0);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        centerpanel.add(jPanel8);
        jPanel8.setBounds(310, 230, 0, 0);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(152, 152, 152));
        jLabel2.setText("Front side");
        centerpanel.add(jLabel2);
        jLabel2.setBounds(80, 40, 80, 20);

        Front_Text.setBackground(new java.awt.Color(213, 213, 213));
        Front_Text.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Front_Text.setForeground(new java.awt.Color(152, 152, 152));
        Front_Text.setText("Enter text here");
        Front_Text.setBorder(null);
        Front_Text.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Front_Text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Front_TextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Front_TextFocusLost(evt);
            }
        });
        centerpanel.add(Front_Text);
        Front_Text.setBounds(80, 70, 920, 210);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Back side");
        centerpanel.add(jLabel3);
        jLabel3.setBounds(80, 280, 80, 30);

        Back_Text.setBackground(new java.awt.Color(213, 213, 213));
        Back_Text.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Back_Text.setForeground(new java.awt.Color(153, 153, 153));
        Back_Text.setText("Enter text here");
        Back_Text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Back_TextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Back_TextFocusLost(evt);
            }
        });
        Back_Text.addActionListener(this::Back_TextActionPerformed);
        centerpanel.add(Back_Text);
        Back_Text.setBounds(80, 310, 920, 190);

        getContentPane().add(centerpanel);
        centerpanel.setBounds(100, 150, 1080, 530);

        Home_Label.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        Home_Label.setForeground(new java.awt.Color(153, 153, 153));
        Home_Label.setText("Home/ Java Language/");
        getContentPane().add(Home_Label);
        Home_Label.setBounds(140, 80, 160, 50);

        NextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arr.png"))); // NOI18N
        NextButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        getContentPane().add(NextButton);
        NextButton.setBounds(100, 90, 30, 30);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel1.setText("Add new card");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 90, 110, 30);

        tickButton.setBackground(new java.awt.Color(0, 153, 255));
        tickButton.setForeground(new java.awt.Color(255, 255, 255));
        tickButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tick1.png"))); // NOI18N
        tickButton.setBorder(null);
        tickButton.addActionListener(this::tickButtonActionPerformed);
        getContentPane().add(tickButton);
        tickButton.setBounds(1110, 100, 70, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_ButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Home_ButtonActionPerformed

    private void tickButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tickButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tickButtonActionPerformed

    private void Back_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Back_TextActionPerformed

    private void Front_TextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Front_TextFocusGained
        // TODO add your handling code here:
        if(Front_Text.getText().equals("Enter text here")){
           Front_Text.setText("");
        }
    }//GEN-LAST:event_Front_TextFocusGained

    private void Front_TextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Front_TextFocusLost
        // TODO add your handling code here:
        if(Front_Text.getText().equals("")){
           Front_Text.setText("Enter text here");
        }
    }//GEN-LAST:event_Front_TextFocusLost

    private void Back_TextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Back_TextFocusGained
        // TODO add your handling code here:
        if(Back_Text.getText().equals("Enter text here")){
           Back_Text.setText("");
        }
    }//GEN-LAST:event_Back_TextFocusGained

    private void Back_TextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Back_TextFocusLost
        // TODO add your handling code here:
        if(Back_Text.getText().equals("")){
           Back_Text.setText("Enter text here");
        }
    }//GEN-LAST:event_Back_TextFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CreateFlashcards().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Back_Text;
    private javax.swing.JTextField Front_Text;
    private javax.swing.JButton Home_Button;
    private javax.swing.JLabel Home_Label;
    private javax.swing.JButton Library_Button;
    private javax.swing.JLabel Logo_label;
    private javax.swing.JButton NextButton;
    private javax.swing.JPanel centerpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton tickButton;
    private javax.swing.JPanel topPanel1;
    // End of variables declaration//GEN-END:variables
}
