/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.UserModel;

/**
 *
 * @author LENOVO
 */
public class CreateFlashcards extends javax.swing.JFrame {


    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateFlashcards.class.getName());
    
    private JPanel mainPanel;
    private CardLayout cardLayout;
    private final int deckId;
    private UserModel currentUser;
    private String deckName;
    private JTextField NumberOfCardsCreated;
    /**
     * Creates new form CreateFlashcards
     */
    public CreateFlashcards(Studycards2 studyPage, String deckName, UserModel currentUser, int deckId) {
    this.deckId = deckId;          // keep ID hidden for database use
    this.currentUser = currentUser; // ✅ store the user for later use
    this.deckName = deckName;      // ✅ store the deck name
    initComponents();
    setSize(1285, 760);

    NewDeckName.setText(deckName); // now works, deckName is a String

    // ✅ Log the deckId for debugging
    logger.info("Opened CreateFlashcards for deckId: " + deckId);
}

    // Default constructor (optional, for testing)
    public CreateFlashcards() {
        initComponents();
        setSize(1285, 760);
        this.deckId = 0;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel1 = new javax.swing.JPanel();
        Home_Button = new javax.swing.JButton();
        Logo_label = new javax.swing.JLabel();
        Library_Button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        centerpanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FrontTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        BackTextArea = new javax.swing.JTextArea();
        GoBackButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        NewDeckName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        topPanel1.setBackground(new java.awt.Color(255, 255, 255));
        topPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Home_Button.setBackground(new java.awt.Color(254, 254, 254));
        Home_Button.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        Home_Button.setText("Home");
        Home_Button.setBorder(null);
        Home_Button.addActionListener(this::Home_ButtonActionPerformed);

        Logo_label.setBackground(new java.awt.Color(254, 254, 254));
        Logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/122.png"))); // NOI18N

        Library_Button.setBackground(new java.awt.Color(254, 254, 254));
        Library_Button.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        Library_Button.setText("Library");
        Library_Button.setBorder(null);

        jLabel4.setBackground(new java.awt.Color(254, 254, 254));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/13.png"))); // NOI18N

        javax.swing.GroupLayout topPanel1Layout = new javax.swing.GroupLayout(topPanel1);
        topPanel1.setLayout(topPanel1Layout);
        topPanel1Layout.setHorizontalGroup(
            topPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(Logo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Home_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Library_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 773, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(145, 145, 145))
        );
        topPanel1Layout.setVerticalGroup(
            topPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanel1Layout.createSequentialGroup()
                .addGroup(topPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(topPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Logo_label)
                        .addGroup(topPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(Home_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(topPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(Library_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(topPanel1);
        topPanel1.setBounds(0, 0, 1330, 70);

        centerpanel.setBackground(new java.awt.Color(255, 255, 255));
        centerpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        centerpanel.setLayout(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        centerpanel.add(jPanel5);
        jPanel5.setBounds(120, 230, 0, 0);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        centerpanel.add(jPanel8);
        jPanel8.setBounds(310, 230, 0, 0);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(152, 152, 152));
        jLabel2.setText("Front side");
        centerpanel.add(jLabel2);
        jLabel2.setBounds(80, 40, 80, 20);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Back side");
        centerpanel.add(jLabel3);
        jLabel3.setBounds(80, 280, 80, 30);

        jScrollPane1.setViewportView(null);

        FrontTextArea.setBackground(new java.awt.Color(213, 213, 213));
        FrontTextArea.setColumns(20);
        FrontTextArea.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        FrontTextArea.setForeground(new java.awt.Color(153, 153, 153));
        FrontTextArea.setRows(5);
        FrontTextArea.setText("Enter text here");
        FrontTextArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FrontTextAreaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FrontTextAreaFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(FrontTextArea);

        centerpanel.add(jScrollPane1);
        jScrollPane1.setBounds(80, 70, 920, 180);

        BackTextArea.setBackground(new java.awt.Color(213, 213, 213));
        BackTextArea.setColumns(20);
        BackTextArea.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        BackTextArea.setForeground(new java.awt.Color(153, 153, 153));
        BackTextArea.setRows(5);
        BackTextArea.setText("Enter text here");
        BackTextArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BackTextAreaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BackTextAreaFocusLost(evt);
            }
        });
        jScrollPane4.setViewportView(BackTextArea);

        centerpanel.add(jScrollPane4);
        jScrollPane4.setBounds(80, 320, 920, 170);

        getContentPane().add(centerpanel);
        centerpanel.setBounds(100, 150, 1080, 530);

        GoBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arr.png"))); // NOI18N
        GoBackButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        GoBackButton.addActionListener(this::GoBackButtonActionPerformed);
        getContentPane().add(GoBackButton);
        GoBackButton.setBounds(100, 90, 30, 30);

        SaveButton.setBackground(new java.awt.Color(0, 153, 255));
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tick1.png"))); // NOI18N
        SaveButton.setBorder(null);
        SaveButton.addActionListener(this::SaveButtonActionPerformed);
        getContentPane().add(SaveButton);
        SaveButton.setBounds(1110, 100, 70, 40);

        NewDeckName.setBackground(new java.awt.Color(240, 240, 240));
        NewDeckName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        NewDeckName.setBorder(null);
        getContentPane().add(NewDeckName);
        NewDeckName.setBounds(150, 90, 950, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_ButtonActionPerformed
        // TODO add your handling code here:
       

    }//GEN-LAST:event_Home_ButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void GoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonActionPerformed
        // TODO add your handling code here:
        // Same behavior for arrow/tick button: go back to Dashtwo
        

    }//GEN-LAST:event_GoBackButtonActionPerformed

    private void FrontTextAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FrontTextAreaFocusGained
        // TODO add your handling code here:
        if(FrontTextArea.getText().equals("Enter text here")){
            FrontTextArea.setText("");
        }
    }//GEN-LAST:event_FrontTextAreaFocusGained

    private void FrontTextAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FrontTextAreaFocusLost
        // TODO add your handling code here:
        if(FrontTextArea.getText().equals("")){
            FrontTextArea.setText("Enter text here");
        }
    }//GEN-LAST:event_FrontTextAreaFocusLost

    private void BackTextAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BackTextAreaFocusGained
        // TODO add your handling code here:
        if(BackTextArea.getText().equals("Enter text here")){
            BackTextArea.setText("");
        }
    }//GEN-LAST:event_BackTextAreaFocusGained

    private void BackTextAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BackTextAreaFocusLost
        // TODO add your handling code here:
        if(BackTextArea.getText().equals("")){
            BackTextArea.setText("Enter text here");
        }
    }//GEN-LAST:event_BackTextAreaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CreateFlashcards().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BackTextArea;
    private javax.swing.JTextArea FrontTextArea;
    private javax.swing.JButton GoBackButton;
    private javax.swing.JButton Home_Button;
    private javax.swing.JButton Library_Button;
    private javax.swing.JLabel Logo_label;
    private javax.swing.JTextField NewDeckName;
    private javax.swing.JButton SaveButton;
    private javax.swing.JPanel centerpanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel topPanel1;
    // End of variables declaration//GEN-END:variables

    public JTextArea getFrontTextArea() {
        return FrontTextArea;
    }
    public JTextArea getBackTextArea() {
        return BackTextArea;
    }
    public JTextField getDeckNameField() {
        return NewDeckName;
    }
    public void HomeButtonListener(ActionListener listener){
    Home_Button.addActionListener(listener);
    }
    public void GoBackButtonListener(ActionListener listener){
    GoBackButton.addActionListener(listener);
    }
    public void SaveButtonListener(ActionListener listener){
    SaveButton.addActionListener(listener);
    }
    
    
}
