package view;

import controller.LoginController;
import controller.UserBasedFlashcardOwnershipController;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionListener;
import model.UserModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JScrollBar;
import view.Login;
import view.Dashtwo;


public class Dashtwo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashtwo.class.getName());

  private JPanel mainPanel;
    private CardLayout cardLayout;
    // Track the currently active dashboard
    private static Dashtwo ACTIVE_DASHBOARD;
   private boolean isDarkMode;
 //   private final UserModel currentUser;
       // Keep track of the current logged-in user
        private JButton createDeckButton;

        private JButton createCardsButton; // grey button shown in image
        private int createdDeckId = -1;
        private final Login loginView = null;

        private Dashtwo dashtwoView;
   
    private UserModel currentUser;
    
        public int getCreatedDeckId() { 
            return createdDeckId; }

        private JButton createButton;
        private java.util.List<JButton> deckButtons = new ArrayList<>();
     
        // Track if user has any decks
        private boolean hasDecks = false;

        // Panel that holds deck buttons vertically
        private JPanel deckContainer;

        // Controls whether we auto-open CreateFlashcards after creating a deck
        private boolean openFlashcardsOnCreate = false; // default: stay on Dashtwo
        private Studycards2 studyPage;   // 🔑 keep one reference

    // === Constructors ===
    /** Creates new form Dashtwo (preferred: with user context) */
    public Dashtwo() {
       initComponents();
       setSize(1285, 760);

    }
    
    // Entry point if this frame is run directly
    public static void main(String[] args) {
         java.awt.EventQueue.invokeLater(() -> new Dashtwo().setVisible(true));
         
        }
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountPopupMenu = new javax.swing.JPopupMenu();
        accountMenuItem = new javax.swing.JMenuItem();
        darkModeMenuItem = new javax.swing.JMenuItem();
        fontSizeMenuItem = new javax.swing.JMenuItem();
        studyHistoryMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        topPanel1 = new javax.swing.JPanel();
        Home_Button = new javax.swing.JButton();
        Logo_label = new javax.swing.JLabel();
        Library_Button = new javax.swing.JButton();
        accountButton = new javax.swing.JButton();
        scrollbar2 = new java.awt.Scrollbar();
        Home_Label = new javax.swing.JLabel();
        CreateButton = new javax.swing.JButton();
        DeckOrganizationButton = new javax.swing.JButton();
        scrollPane1 = new javax.swing.JScrollPane();
        DeleteDeckButton = new javax.swing.JButton();
        ArchiveButton = new javax.swing.JButton();
        FavoritesButton = new javax.swing.JButton();

        accountPopupMenu.setBackground(new java.awt.Color(102, 102, 102));
        accountPopupMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(200, 200, 200), new java.awt.Color(150, 150, 150), new java.awt.Color(80, 80, 82), new java.awt.Color(100, 100, 100)));

        accountMenuItem.setText("Account");
        accountMenuItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(200, 200, 200), new java.awt.Color(150, 150, 150), new java.awt.Color(80, 80, 80), new java.awt.Color(100, 100, 100)));
        accountPopupMenu.add(accountMenuItem);

        darkModeMenuItem.setText("Dark mode/ Light mode");
        accountPopupMenu.add(darkModeMenuItem);

        fontSizeMenuItem.setText("Font size");
        accountPopupMenu.add(fontSizeMenuItem);

        studyHistoryMenuItem.setText("Study history");
        accountPopupMenu.add(studyHistoryMenuItem);

        logoutMenuItem.setText("Log out");
        accountPopupMenu.add(logoutMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().setLayout(null);

        topPanel1.setBackground(new java.awt.Color(255, 255, 255));
        topPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Home_Button.setBackground(new java.awt.Color(254, 254, 254));
        Home_Button.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        Home_Button.setText("Home");
        Home_Button.setBorder(null);
        Home_Button.addActionListener(this::Home_ButtonActionPerformed);

        Logo_label.setBackground(new java.awt.Color(254, 254, 254));
        Logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/122.png"))); // NOI18N

        Library_Button.setBackground(new java.awt.Color(254, 254, 254));
        Library_Button.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        Library_Button.setText("Library");
        Library_Button.setBorder(null);

        accountButton.setBackground(new java.awt.Color(254, 254, 254));
        accountButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/13_1.png"))); // NOI18N
        accountButton.setBorder(null);
        accountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountButtonMouseClicked(evt);
            }
        });
        accountButton.addActionListener(this::accountButtonActionPerformed);

        javax.swing.GroupLayout topPanel1Layout = new javax.swing.GroupLayout(topPanel1);
        topPanel1.setLayout(topPanel1Layout);
        topPanel1Layout.setHorizontalGroup(
            topPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(Logo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Home_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Library_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 774, Short.MAX_VALUE)
                .addComponent(accountButton)
                .addGap(144, 144, 144))
        );
        topPanel1Layout.setVerticalGroup(
            topPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanel1Layout.createSequentialGroup()
                .addGroup(topPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo_label)
                    .addGroup(topPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Home_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Library_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(accountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(topPanel1);
        topPanel1.setBounds(0, 0, 1330, 70);

        Home_Label.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Home_Label.setText("Home");
        getContentPane().add(Home_Label);
        Home_Label.setBounds(100, 90, 140, 40);

        CreateButton.setBackground(new java.awt.Color(0, 153, 255));
        CreateButton.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        CreateButton.setForeground(new java.awt.Color(255, 255, 255));
        CreateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/create.png"))); // NOI18N
        CreateButton.setText("  Create ");
        CreateButton.setBorder(null);
        CreateButton.addActionListener(this::CreateButtonActionPerformed);
        getContentPane().add(CreateButton);
        CreateButton.setBounds(1060, 110, 120, 30);

        DeckOrganizationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-17 205936.png"))); // NOI18N
        DeckOrganizationButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        DeckOrganizationButton.addActionListener(this::DeckOrganizationButtonActionPerformed);
        getContentPane().add(DeckOrganizationButton);
        DeckOrganizationButton.setBounds(1020, 110, 30, 30);

        scrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        getContentPane().add(scrollPane1);
        scrollPane1.setBounds(100, 150, 1080, 530);

        DeleteDeckButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dd.png"))); // NOI18N
        DeleteDeckButton.addActionListener(this::DeleteDeckButtonActionPerformed);
        getContentPane().add(DeleteDeckButton);
        DeleteDeckButton.setBounds(980, 110, 30, 30);

        ArchiveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/archive.png"))); // NOI18N
        ArchiveButton.addActionListener(this::ArchiveButtonActionPerformed);
        getContentPane().add(ArchiveButton);
        ArchiveButton.setBounds(940, 110, 30, 30);

        FavoritesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star.png"))); // NOI18N
        FavoritesButton.addActionListener(this::FavoritesButtonActionPerformed);
        getContentPane().add(FavoritesButton);
        FavoritesButton.setBounds(900, 110, 30, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//
    private void accountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountButtonActionPerformed
        // TODO add your handling code here:
//      openUserBasedFlashcardOwnership(); // ✅ open the page
    }//GEN-LAST:event_accountButtonActionPerformed

    private void accountButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountButtonMouseClicked
        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) { // Left click only
            int x = accountButton.getWidth() - accountPopupMenu.getPreferredSize().width;
            int y = accountButton.getHeight();
            accountPopupMenu.show(accountButton, x, y);
        }
    }//GEN-LAST:event_accountButtonMouseClicked

    private void Home_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_ButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Home_ButtonActionPerformed

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        // TODO add your handling code here:
        // ✅ Just call the helper method
      


    }//GEN-LAST:event_CreateButtonActionPerformed

    private void DeckOrganizationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeckOrganizationButtonActionPerformed
        // TODO add your handling code here:
      



    }//GEN-LAST:event_DeckOrganizationButtonActionPerformed

    private void ArchiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchiveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArchiveButtonActionPerformed

    private void FavoritesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavoritesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FavoritesButtonActionPerformed

    private void DeleteDeckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteDeckButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteDeckButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArchiveButton;
    private javax.swing.JButton CreateButton;
    private javax.swing.JButton DeckOrganizationButton;
    private javax.swing.JButton DeleteDeckButton;
    private javax.swing.JButton FavoritesButton;
    private javax.swing.JButton Home_Button;
    private javax.swing.JLabel Home_Label;
    private javax.swing.JButton Library_Button;
    private javax.swing.JLabel Logo_label;
    private javax.swing.JButton accountButton;
    private javax.swing.JMenuItem accountMenuItem;
    private javax.swing.JPopupMenu accountPopupMenu;
    private javax.swing.JMenuItem darkModeMenuItem;
    private javax.swing.JMenuItem fontSizeMenuItem;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JScrollPane scrollPane1;
    private java.awt.Scrollbar scrollbar2;
    private javax.swing.JMenuItem studyHistoryMenuItem;
    private javax.swing.JPanel topPanel1;
    // End of variables declaration//GEN-END:variables

    public void AccountButtonListener(ActionListener listener){
        accountButton.addActionListener(listener);
    }
    public void CreateButtonListener(ActionListener listener){
        CreateButton.addActionListener(listener);
    }
    public void DeleteDeckButtonListener(ActionListener listener){
        DeleteDeckButton.addActionListener(listener);
    }
    public void DeckOrganizationButtonListener(ActionListener listener){
        DeckOrganizationButton.addActionListener(listener);
    }
    public void ArchiveButtonListener(ActionListener listener){
        ArchiveButton.addActionListener(listener);
    }
    public void FavoritesButtonListener(ActionListener listener){
        FavoritesButton.addActionListener(listener);
    }

    // Example getters you must add in Dashtwo.java
    public JMenuItem getDarkModeMenuItem() { return darkModeMenuItem; }
    public JMenuItem getFontSizeMenuItem() { return fontSizeMenuItem; }
    public JMenuItem getStudyHistoryMenuItem() { return studyHistoryMenuItem; }
    public JMenuItem getLogoutMenuItem() { return logoutMenuItem; }
    public JMenuItem getAccountMenuItem() { return accountMenuItem; }

    public JPanel getTopPanel() { return topPanel1; }
    public JButton getAccountButton() { return accountButton; }
    public JLabel getHomeLabel() { return Home_Label; }
    public JScrollPane getScrollPane() { return scrollPane1; }

    void addDeckButton(String deckName, int deckId) {
        JButton deckButton = new JButton(deckName);
    }
    public void saveDeckToStorage(int deckId, String deckName) {
    }
}





