/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AccountController;
import controller.DeckController;
import java.awt.Color;
import java.awt.Component;



/**
 *
 * @author bipin ranabhat
 */
public class Dashboard extends javax.swing.JFrame {
    
    private DeckController deckController = new DeckController();
    private AccountController accountController;  // Add this near the top with other fields
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form dashboard
     */
    public Dashboard() {
        initComponents();
        
        FontSize.setText("Font Size");           // instead of "jMenuItem3"
        StudyHistory.setText("Study History");   // instead of "jMenuItem4"
        Logout.setText("Log out");
       
  
        accountController = new controller.AccountController(this);  // Now assigned
    // Show popup menu when profile button (jButton2) is clicked
        // === NEW: Initialize DeckController ===
        deckController = new DeckController();

        // === Connect the "Create" button (the blue + Create button in Dashboard) ===
        // Replace "createButton" with your actual button variable name from GUI builder
        // Common names: jButtonCreate, createButton, btnCreate, etc.
        jButton1.addActionListener(e -> openCreateDeckDialog());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Account = new javax.swing.JMenuItem();
        darkligthmode = new javax.swing.JMenuItem();
        FontSize = new javax.swing.JMenuItem();
        StudyHistory = new javax.swing.JMenuItem();
        Logout = new javax.swing.JMenuItem();
        topPanel1 = new javax.swing.JPanel();
        Home_Button = new javax.swing.JButton();
        Logo_label = new javax.swing.JLabel();
        Library_Button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Home_Label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        Account.setIcon(new javax.swing.ImageIcon("C:\\Users\\bipin ranabhat\\OneDrive\\Documents\\img\\menuAcc.png")); // NOI18N
        Account.setText("Account");
        Account.addActionListener(this::AccountActionPerformed);
        jPopupMenu1.add(Account);

        darkligthmode.setIcon(new javax.swing.ImageIcon("C:\\Users\\bipin ranabhat\\OneDrive\\Documents\\img\\darkmode.png")); // NOI18N
        darkligthmode.setText("Dark/Light Mode");
        darkligthmode.addActionListener(this::darkligthmodeActionPerformed);
        jPopupMenu1.add(darkligthmode);

        FontSize.setIcon(new javax.swing.ImageIcon("C:\\Users\\bipin ranabhat\\OneDrive\\Documents\\img\\fontsize.png")); // NOI18N
        FontSize.setText("jMenuItem3");
        jPopupMenu1.add(FontSize);

        StudyHistory.setIcon(new javax.swing.ImageIcon("C:\\Users\\bipin ranabhat\\OneDrive\\Documents\\img\\studyhistory.png")); // NOI18N
        StudyHistory.setText("jMenuItem4");
        StudyHistory.addActionListener(this::StudyHistoryActionPerformed);
        jPopupMenu1.add(StudyHistory);

        Logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\bipin ranabhat\\OneDrive\\Documents\\img\\logout.png")); // NOI18N
        Logout.setText("jMenuItem5");
        jPopupMenu1.add(Logout);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        getContentPane().setLayout(null);

        topPanel1.setBackground(new java.awt.Color(255, 255, 255));
        topPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        topPanel1.setLayout(null);

        Home_Button.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        Home_Button.setText("Home");
        Home_Button.setBorder(null);
        Home_Button.addActionListener(this::Home_ButtonActionPerformed);
        topPanel1.add(Home_Button);
        Home_Button.setBounds(190, 20, 80, 40);

        Logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        topPanel1.add(Logo_label);
        Logo_label.setBounds(100, 10, 60, 50);

        Library_Button.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        Library_Button.setText("Library");
        Library_Button.setBorder(null);
        Library_Button.addActionListener(this::Library_ButtonActionPerformed);
        topPanel1.add(Library_Button);
        Library_Button.setBounds(290, 20, 100, 40);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\bipin ranabhat\\OneDrive\\Documents\\img\\acc.png")); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(this::jButton2ActionPerformed);
        topPanel1.add(jButton2);
        jButton2.setBounds(1150, 10, 60, 56);

        getContentPane().add(topPanel1);
        topPanel1.setBounds(0, 0, 1330, 70);

        Home_Label.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Home_Label.setText("Home");
        getContentPane().add(Home_Label);
        Home_Label.setBounds(110, 100, 112, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jButton1.setText(" Create ");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 90, 850, 79);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("QUICK START ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 50, 130, 28);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(180, 170, 1000, 410);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\bipin ranabhat\\OneDrive\\Documents\\img\\background .png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1330, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Home_ButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CreateDialog dialog = new CreateDialog(this, true);  // true = modal
        dialog.setDeckController(deckController);  // We'll add this setter
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountActionPerformed
    // TODO add your handling code here:
    // TODO add your handling code here:
    // TODO add your handling code here:

    private void darkligthmodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkligthmodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_darkligthmodeActionPerformed
    // TODO add your handling code here:


    private void StudyHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudyHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudyHistoryActionPerformed

    private void Library_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Library_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Library_ButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }
    
    // === ADD THESE METHODS AT THE END OF Dashboard.java (before the closing }) ===

    public javax.swing.JPanel getTopPanel() {
        return topPanel1;
    }

    public javax.swing.JPanel getMainPanel() {
        return jPanel1;
    }

    public javax.swing.JMenuItem getDarkLightModeMenuItem() {
        return darkligthmode;
    }

    public javax.swing.JMenuItem getAccountMenuItem() {
        return Account;
    }

    public javax.swing.JMenuItem getStudyHistoryMenuItem() {
        return StudyHistory;
    }

    public javax.swing.JMenuItem getLogoutMenuItem() {
        return Logout;
    }

    public javax.swing.JPopupMenu getProfilePopupMenu() {
        return jPopupMenu1;
    }

    public javax.swing.JButton getProfileButton() {
        return jButton2;
    }
    
    public javax.swing.JButton getHomeButton() {
    return Home_Button;
    }

    public javax.swing.JButton getLibraryButton() {
        return Library_Button;
    }

    public javax.swing.JLabel getLogoLabel() {
        return Logo_label;
    }

    public javax.swing.JButton getProfileIconButton() {
        return jButton2;
    }

    
    public javax.swing.JButton getCreateButton() {
    return jButton1;  // Replace with your actual Create button variable name!
    // Common names: jButtonCreate, btnCreate, createButton, jButton1, etc.
}

    public void applyLightTheme() {
        getContentPane().setBackground(Color.WHITE);
        getTopPanel().setBackground(Color.WHITE);
        getMainPanel().setBackground(Color.WHITE);  // ← THIS WAS MISSING or not restored properly

        // Restore Create button
        getCreateButton().setBackground(new Color(204, 204, 204));  // original color from initComponents
        getCreateButton().setForeground(Color.BLACK);

        // Restore Home & Library buttons
        getHomeButton().setBackground(new Color(240, 240, 240));
        getHomeButton().setForeground(Color.BLACK);
        getLibraryButton().setBackground(new Color(240, 240, 240));
        getLibraryButton().setForeground(Color.BLACK);

        // Restore all text to black
        setForegroundRecursively(getContentPane(), Color.BLACK);

        getDarkLightModeMenuItem().setText("Dark/Light Mode");
    }

    public void applyDarkTheme() {
        getContentPane().setBackground(new Color(30, 30, 30));
        getTopPanel().setBackground(new Color(20, 20, 20));
        getMainPanel().setBackground(new Color(45, 45, 45));  // ← Make sure this is set

        // Darken buttons
        getCreateButton().setBackground(new Color(70, 70, 70));
        getCreateButton().setForeground(Color.WHITE);

        getHomeButton().setBackground(new Color(50, 50, 50));
        getHomeButton().setForeground(Color.WHITE);
        getLibraryButton().setBackground(new Color(50, 50, 50));
        getLibraryButton().setForeground(Color.WHITE);
    
    // All text white
    setForegroundRecursively(getContentPane(), Color.WHITE);
    
    getDarkLightModeMenuItem().setText("Light Mode");
    }

    private void setForegroundRecursively(Component component, Color color) {
        component.setForeground(color);
        if (component instanceof java.awt.Container container) {
            for (Component child : container.getComponents()) {
                setForegroundRecursively(child, color);
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Account;
    private javax.swing.JMenuItem FontSize;
    private javax.swing.JButton Home_Button;
    private javax.swing.JLabel Home_Label;
    private javax.swing.JButton Library_Button;
    private javax.swing.JLabel Logo_label;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenuItem StudyHistory;
    private javax.swing.JMenuItem darkligthmode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPanel topPanel1;
    // End of variables declaration//GEN-END:variables

    private void openCreateDeckDialog() {
        CreateDialog dialog = new CreateDialog(this, true);  // modal dialog
        dialog.setDeckController(deckController);            // pass the controller
        dialog.setVisible(true);
    }


}
