package view;



public class Dashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(Dashboard.class.getName());

    // Track the currently active dashboard
 
    /** constructor (needed for GUI builder or fallback) */
    public Dashboard() {
        initComponents();

    }

    private void showFontSizeOptions() {

    }

    private void openStudyHistory() {
     
    }
        // === Create button clicks ===

    
    private void openNewDeckDialog() {
       
    
        }
    
    
    private void openStudycards2() {
        
    }
    
    
    
    // === Deck area setup using scrollPane1 ===
    private void initDeckContainer() {
  
        
    }




    
    // Entry point if this frame is run directly
    public static void main(String[] args) {
 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountPopupMenu = new javax.swing.JPopupMenu();
        accountMenuItem = new javax.swing.JMenuItem();
        darkModeMenuItem = new javax.swing.JMenuItem();
        fontSizeMenuItem = new javax.swing.JMenuItem();
        studyHistoryMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        topPanel1 = new javax.swing.JPanel();
        Home_Button = new javax.swing.JButton();
        Logo_label = new javax.swing.JLabel();
        Library_Button = new javax.swing.JButton();
        accountButton = new javax.swing.JButton();
        scrollbar2 = new java.awt.Scrollbar();
        Home_Label = new javax.swing.JLabel();
        CreateButton = new javax.swing.JButton();
        DeckOrganizationButton = new javax.swing.JButton();
        scrollPane1 = new javax.swing.JScrollPane();

        accountPopupMenu.setBackground(new java.awt.Color(102, 102, 102));
        accountPopupMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(200, 200, 200), new java.awt.Color(150, 150, 150), new java.awt.Color(80, 80, 82), new java.awt.Color(100, 100, 100)));

        accountMenuItem.setText("Account");
        accountMenuItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(200, 200, 200), new java.awt.Color(150, 150, 150), new java.awt.Color(80, 80, 80), new java.awt.Color(100, 100, 100)));
        accountPopupMenu.add(accountMenuItem);

        darkModeMenuItem.setText("Dark mode/ Light mode");
        accountPopupMenu.add(darkModeMenuItem);

        fontSizeMenuItem.setText("Font size");
        accountPopupMenu.add(fontSizeMenuItem);

        studyHistoryMenuItem.setText("Study history");
        accountPopupMenu.add(studyHistoryMenuItem);

        logoutMenuItem.setText("Log out");
        accountPopupMenu.add(logoutMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().setLayout(null);

        topPanel1.setBackground(new java.awt.Color(255, 255, 255));
        topPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        topPanel1.setLayout(null);

        Home_Button.setBackground(new java.awt.Color(254, 254, 254));
        Home_Button.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        Home_Button.setText("Home");
        Home_Button.setBorder(null);
        Home_Button.addActionListener(this::Home_ButtonActionPerformed);
        topPanel1.add(Home_Button);
        Home_Button.setBounds(190, 21, 60, 20);

        Logo_label.setBackground(new java.awt.Color(254, 254, 254));
        Logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/122.png"))); // NOI18N
        topPanel1.add(Logo_label);
        Logo_label.setBounds(100, 1, 80, 65);

        Library_Button.setBackground(new java.awt.Color(254, 254, 254));
        Library_Button.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        Library_Button.setText("Library");
        Library_Button.setBorder(null);
        topPanel1.add(Library_Button);
        Library_Button.setBounds(280, 11, 70, 40);

        accountButton.setBackground(new java.awt.Color(254, 254, 254));
        accountButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/13_1.png"))); // NOI18N
        accountButton.setBorder(null);
        accountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountButtonMouseClicked(evt);
            }
        });
        accountButton.addActionListener(this::accountButtonActionPerformed);
        topPanel1.add(accountButton);
        accountButton.setBounds(1124, 1, 61, 65);
        topPanel1.add(scrollbar2);
        scrollbar2.setBounds(0, 0, 0, 0);

        getContentPane().add(topPanel1);
        topPanel1.setBounds(0, 0, 1330, 70);

        Home_Label.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Home_Label.setText("Home");
        getContentPane().add(Home_Label);
        Home_Label.setBounds(100, 90, 140, 40);

        CreateButton.setBackground(new java.awt.Color(0, 153, 255));
        CreateButton.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        CreateButton.setForeground(new java.awt.Color(255, 255, 255));
        CreateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/create.png"))); // NOI18N
        CreateButton.setText("  Create ");
        CreateButton.setBorder(null);
        CreateButton.addActionListener(this::CreateButtonActionPerformed);
        getContentPane().add(CreateButton);
        CreateButton.setBounds(1060, 110, 120, 30);

        DeckOrganizationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-17 205936.png"))); // NOI18N
        DeckOrganizationButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        DeckOrganizationButton.addActionListener(this::DeckOrganizationButtonActionPerformed);
        getContentPane().add(DeckOrganizationButton);
        DeckOrganizationButton.setBounds(1020, 110, 30, 30);

        scrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        getContentPane().add(scrollPane1);
        scrollPane1.setBounds(100, 150, 1080, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountButtonActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_accountButtonActionPerformed

    private void accountButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountButtonMouseClicked
        
        
    }//GEN-LAST:event_accountButtonMouseClicked

    private void Home_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_ButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Home_ButtonActionPerformed

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        // TODO add your handling code here:
     // ✅ Just call the helper method
 


    }//GEN-LAST:event_CreateButtonActionPerformed

    private void DeckOrganizationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeckOrganizationButtonActionPerformed
        // TODO add your handling code here:
      



    }//GEN-LAST:event_DeckOrganizationButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateButton;
    private javax.swing.JButton DeckOrganizationButton;
    private javax.swing.JButton Home_Button;
    private javax.swing.JLabel Home_Label;
    private javax.swing.JButton Library_Button;
    private javax.swing.JLabel Logo_label;
    private javax.swing.JButton accountButton;
    private javax.swing.JMenuItem accountMenuItem;
    private javax.swing.JPopupMenu accountPopupMenu;
    private javax.swing.JMenuItem darkModeMenuItem;
    private javax.swing.JMenuItem fontSizeMenuItem;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JScrollPane scrollPane1;
    private java.awt.Scrollbar scrollbar2;
    private javax.swing.JMenuItem studyHistoryMenuItem;
    private javax.swing.JPanel topPanel1;
    // End of variables declaration//GEN-END:variables


}




