/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
/**
 *
 * @author ashishchaudhary
 */
public class FlipAndSwitch extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FlipAndSwitch.class.getName());

    /**
     * Creates new form
     */
    public FlipAndSwitch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        lblCardCount = new javax.swing.JLabel();
        lblSource = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblDifficulty = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        btnNext.setText("jButton4");
        jPanel1.add(btnNext);
        btnNext.setBounds(420, 270, 80, 50);

        btnPrev.setText("jButton1");
        jPanel1.add(btnPrev);
        btnPrev.setBounds(180, 270, 80, 50);

        lblCardCount.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblCardCount.setText("Card: [3/10]");
        jPanel1.add(lblCardCount);
        lblCardCount.setBounds(190, 380, 90, 30);

        lblSource.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblSource.setText("Source: 80%");
        jPanel1.add(lblSource);
        lblSource.setBounds(300, 380, 90, 30);

        lblCategory.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblCategory.setText("Category: Programming");
        jPanel1.add(lblCategory);
        lblCategory.setBounds(140, 420, 170, 30);

        lblDifficulty.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblDifficulty.setText("DIfficulty: Medium");
        jPanel1.add(lblDifficulty);
        lblDifficulty.setBounds(400, 410, 190, 50);
        jPanel1.add(cardPanel);
        cardPanel.setBounds(170, 80, 360, 140);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 680, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FlipAndSwitch().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCardCount;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDifficulty;
    private javax.swing.JLabel lblSource;
    // End of variables declaration//GEN-END:variables
    // GETTERS FOR CONTROLLER ACCESS
    public javax.swing.JPanel getCardPanel() {
        return cardPanel;
    }
    // ADD THIS NEW METHOD for your controller
public CardsPanel getCardsPanelComponent() {
    return (CardsPanel) cardPanel;
}
    
    public javax.swing.JButton getBtnPrev() {
        return btnPrev;
    }
    
    public javax.swing.JButton getBtnNext() {
        return btnNext;
    }
    
    public javax.swing.JLabel getLblCardCount() {
        return lblCardCount;
    }
    
    public javax.swing.JLabel getLblScore() {
        return lblSource;  // Note: You have lblSource instead of lblScore
    }
    
    public javax.swing.JLabel getLblCategory() {
        return lblCategory;
    }
    
    public javax.swing.JLabel getLblDifficulty() {
        return lblDifficulty;
    }
    
    // SETTERS FOR CONTROLLER TO UPDATE LABELS
    public void setCardCount(String text) {
        lblCardCount.setText(text);
    }
    
    public void setScore(String text) {
        lblSource.setText(text);
    }
    
    public void setCategory(String text) {
        lblCategory.setText(text);
    }
    
    public void setDifficulty(String text) {
        lblDifficulty.setText(text);
    }
    
    // ACTION LISTENER SETTERS
    public void addPrevButtonListener(java.awt.event.ActionListener listener) {
        btnPrev.addActionListener(listener);
    }
    
    public void addNextButtonListener(java.awt.event.ActionListener listener) {
        btnNext.addActionListener(listener);
    }


}
