/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.FlipAndSwipeNavigationController;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author LENOVO
 */
public class FlipAndSwipeNavigation extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FlipAndSwipeNavigation.class.getName());
    private JTextArea BackTextArea;

    

    /**
     * Creates new form FlipAndSwipeNavigation
     */
    public FlipAndSwipeNavigation() {
        initComponents();
        setSize(1285,760);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CardNumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        FrontTextArea = new javax.swing.JTextArea();
        CrossButton = new javax.swing.JButton();
        RightButton = new javax.swing.JButton();
        LeftButton = new javax.swing.JButton();
        DeleteCardButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        CardNumber.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CardNumber.setForeground(new java.awt.Color(102, 102, 102));
        CardNumber.setBorder(null);
        jPanel1.add(CardNumber);
        CardNumber.setBounds(610, 30, 110, 30);

        FrontTextArea.setColumns(20);
        FrontTextArea.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        FrontTextArea.setRows(5);
        FrontTextArea.setBorder(null);
        jScrollPane1.setViewportView(FrontTextArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(280, 70, 720, 550);

        CrossButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x1.png"))); // NOI18N
        CrossButton.setBorder(null);
        CrossButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CrossButton.setPreferredSize(new java.awt.Dimension(26, 32));
        jPanel1.add(CrossButton);
        CrossButton.setBounds(250, 30, 30, 30);

        RightButton.setBackground(new java.awt.Color(150, 150, 150));
        RightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/r.png"))); // NOI18N
        RightButton.setBorder(null);
        jPanel1.add(RightButton);
        RightButton.setBounds(1020, 297, 30, 50);

        LeftButton.setBackground(new java.awt.Color(150, 150, 150));
        LeftButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rr.png"))); // NOI18N
        LeftButton.setBorder(null);
        jPanel1.add(LeftButton);
        LeftButton.setBounds(230, 300, 30, 50);

        DeleteCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dd.png"))); // NOI18N
        jPanel1.add(DeleteCardButton);
        DeleteCardButton.setBounds(1000, 30, 30, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1330, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FlipAndSwipeNavigation().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CardNumber;
    private javax.swing.JButton CrossButton;
    private javax.swing.JButton DeleteCardButton;
    private javax.swing.JTextArea FrontTextArea;
    private javax.swing.JButton LeftButton;
    private javax.swing.JButton RightButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void LeftButtonListener(ActionListener listener){
    LeftButton.addActionListener(listener);
    }
    public void RightButtonListener(ActionListener listener){
    RightButton.addActionListener(listener);
    }
    public void CrosstButtonListener(ActionListener listener){
    CrossButton.addActionListener(listener);
    }
    public void DeleteCardButtonListener(ActionListener listener){
        DeleteCardButton.addActionListener(listener);
    }
    public JTextField getCardNumberField() {
    return CardNumber; // make sure this text field exists in your form
    }
    public JTextArea getFrontTextField() {
    return FrontTextArea; // make sure this text field exists in your form
    }
    public JTextArea getBackTextField() {
    return BackTextArea; // make sure this text field exists in your form
    }
}
