/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author LENOVO
 */
public class ForgotPassword extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ForgotPassword.class.getName());

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
        setSize(380, 380);
        setResizable(false);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        show_password = new javax.swing.JCheckBox();
        username_Text_Field = new javax.swing.JTextField();
        Signup_Title = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        ChangePassword = new javax.swing.JLabel();
        Flashcard_Logo = new javax.swing.JLabel();
        ChangePassword_Field = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        show_password.setBackground(new java.awt.Color(30, 98, 165));
        show_password.setForeground(new java.awt.Color(255, 255, 255));
        show_password.setText("Show password");
        show_password.setBorder(null);
        show_password.addActionListener(this::show_passwordActionPerformed);
        getContentPane().add(show_password);
        show_password.setBounds(240, 300, 110, 18);

        username_Text_Field.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        username_Text_Field.setForeground(new java.awt.Color(102, 102, 102));
        username_Text_Field.setText(" Enter the username");
        username_Text_Field.setBorder(null);
        username_Text_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_Text_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                username_Text_FieldFocusLost(evt);
            }
        });
        username_Text_Field.addActionListener(this::username_Text_FieldActionPerformed);
        getContentPane().add(username_Text_Field);
        username_Text_Field.setBounds(20, 150, 330, 40);

        Signup_Title.setBackground(new java.awt.Color(26, 98, 169));
        Signup_Title.setFont(new java.awt.Font("Cambria", 1, 30)); // NOI18N
        Signup_Title.setForeground(new java.awt.Color(255, 255, 255));
        Signup_Title.setText("Forgot Password");
        getContentPane().add(Signup_Title);
        Signup_Title.setBounds(110, 10, 270, 63);

        Username.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username");
        getContentPane().add(Username);
        Username.setBounds(20, 120, 90, 22);

        ChangePassword.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        ChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        ChangePassword.setText("Change Password ");
        getContentPane().add(ChangePassword);
        ChangePassword.setBounds(20, 220, 150, 22);

        Flashcard_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signupp.png"))); // NOI18N
        Flashcard_Logo.setText("jLabel6");
        getContentPane().add(Flashcard_Logo);
        Flashcard_Logo.setBounds(-50, 0, 170, 150);

        ChangePassword_Field.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        ChangePassword_Field.setForeground(new java.awt.Color(102, 102, 102));
        ChangePassword_Field.setBorder(null);
        getContentPane().add(ChangePassword_Field);
        ChangePassword_Field.setBounds(20, 250, 330, 40);

        jPanel1.setBackground(new java.awt.Color(30, 98, 165));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 370, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_Text_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_Text_FieldFocusGained
        // TODO add your handling code here:
        if(username_Text_Field.getText().equals(" Enter the username")){
            username_Text_Field.setText("");
        }
    }//GEN-LAST:event_username_Text_FieldFocusGained

    private void username_Text_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_Text_FieldFocusLost
        // TODO add your handling code here:
        if(username_Text_Field.getText().equals("")){
            username_Text_Field.setText(" Enter the username");
        }
    }//GEN-LAST:event_username_Text_FieldFocusLost

    private void username_Text_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_Text_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_Text_FieldActionPerformed

    private void show_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_passwordActionPerformed
        // TODO add your handling code here:
        if (show_password.isSelected()) {
            ChangePassword_Field.setEchoChar((char)0); // show text
        } else {
            ChangePassword_Field.setEchoChar('*');     // hide text

        }

    }//GEN-LAST:event_show_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ForgotPassword().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChangePassword;
    private javax.swing.JPasswordField ChangePassword_Field;
    private javax.swing.JLabel Flashcard_Logo;
    private javax.swing.JLabel Signup_Title;
    private javax.swing.JLabel Username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox show_password;
    private javax.swing.JTextField username_Text_Field;
    // End of variables declaration//GEN-END:variables
}
