/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LoginController;
import controller.UserController;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author LENOVO
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        setSize(1285,760);
        

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        CreateAccountButton = new javax.swing.JButton();
        Login = new javax.swing.JLabel();
        ForgotPasswordButton = new javax.swing.JButton();
        password_field = new javax.swing.JPasswordField();
        show_password = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1288, 751));
        getContentPane().setLayout(null);

        Username.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username");
        getContentPane().add(Username);
        Username.setBounds(20, 190, 90, 16);

        Password.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        getContentPane().add(Password);
        Password.setBounds(20, 310, 90, 16);

        username.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        username.setForeground(new java.awt.Color(51, 51, 51));
        username.setText(" Enter the username");
        username.setBorder(null);
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(20, 220, 300, 40);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Or");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 580, 23, 22);

        LoginButton.setBackground(new java.awt.Color(23, 150, 255));
        LoginButton.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.setBorder(null);
        LoginButton.addActionListener(this::LoginButtonActionPerformed);
        getContentPane().add(LoginButton);
        LoginButton.setBounds(130, 510, 80, 40);

        CreateAccountButton.setBackground(new java.awt.Color(23, 150, 255));
        CreateAccountButton.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        CreateAccountButton.setForeground(new java.awt.Color(255, 255, 255));
        CreateAccountButton.setText("Create a new account");
        CreateAccountButton.setBorder(null);
        CreateAccountButton.addActionListener(this::CreateAccountButtonActionPerformed);
        getContentPane().add(CreateAccountButton);
        CreateAccountButton.setBounds(70, 630, 200, 40);

        Login.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("LOGIN");
        getContentPane().add(Login);
        Login.setBounds(160, 40, 190, 50);

        ForgotPasswordButton.setBackground(new java.awt.Color(23, 150, 255));
        ForgotPasswordButton.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        ForgotPasswordButton.setForeground(new java.awt.Color(255, 255, 255));
        ForgotPasswordButton.setText("Forgot password?");
        ForgotPasswordButton.setBorder(null);
        ForgotPasswordButton.addActionListener(this::ForgotPasswordButtonActionPerformed);
        getContentPane().add(ForgotPasswordButton);
        ForgotPasswordButton.setBounds(190, 390, 130, 30);

        password_field.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        password_field.setForeground(new java.awt.Color(51, 51, 51));
        password_field.setBorder(null);
        getContentPane().add(password_field);
        password_field.setBounds(20, 340, 300, 40);

        show_password.setBackground(new java.awt.Color(30, 98, 165));
        show_password.setForeground(new java.awt.Color(255, 255, 255));
        show_password.setText("Show password");
        show_password.setBorder(null);
        show_password.addActionListener(this::show_passwordActionPerformed);
        getContentPane().add(show_password);
        show_password.setBounds(20, 390, 130, 18);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signupp.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 170, 178);

        jPanel1.setBackground(new java.awt.Color(30, 98, 165));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -30, 350, 790);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 65)); // NOI18N
        jLabel1.setText("Flashcard Study ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(570, 270, 540, 120);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 45)); // NOI18N
        jLabel4.setText("Learn More, Stress Less");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(570, 350, 570, 71);

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        jLabel5.setText("Create flashcards and crush exams, with the magic of spaced");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(560, 420, 560, 40);

        jLabel18.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel18.setText("Heart");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(470, 0, 120, 60);

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel9.setText("What is the area of circle?");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1070, 150, 160, 30);

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        jLabel6.setText("repetetion. Join our community of smart learners.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(610, 440, 490, 40);

        jLabel17.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel17.setText("Name the flag");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(1130, 500, 90, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (31).png"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1060, 20, 170, 200);

        jLabel15.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel15.setText("Computer parts");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(420, 500, 110, 40);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (37).png"))); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        getContentPane().add(jLabel16);
        jLabel16.setBounds(1080, 510, 170, 200);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (38).png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1050, 520, 190, 190);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (30).png"))); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jLabel19.setMaximumSize(new java.awt.Dimension(170, 200));
        jLabel19.setMinimumSize(new java.awt.Dimension(170, 200));
        jLabel19.setPreferredSize(new java.awt.Dimension(170, 200));
        getContentPane().add(jLabel19);
        jLabel19.setBounds(400, 20, 170, 200);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (26).png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(370, 30, 170, 200);

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setForeground(new java.awt.Color(232, 232, 232));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (34).png"))); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(380, 510, 170, 200);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (35).png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(400, 520, 170, 200);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (32).png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1090, -10, 250, 260);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image 162 (3).png"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(470, 150, 671, 410);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(1050, 220, 116, 20);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(350, -110, 940, 860);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void CreateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountButtonActionPerformed
        // TODO add your handling code here:
        Signup signupView = new Signup();                      // Create signup window
        UserController SignupController = new UserController(signupView);  
        signupView.setVisible(true);                           // Show signup page
        this.dispose();                         
    }//GEN-LAST:event_CreateAccountButtonActionPerformed

    private void ForgotPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgotPasswordButtonActionPerformed
        // TODO add your handling code here:
        LoginController controller = new LoginController(this);
        
    }//GEN-LAST:event_ForgotPasswordButtonActionPerformed

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        // TODO add your handling code here:
        if(username.getText().equals(" Enter the username")){
            username.setText("");
        }
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
        if(username.getText().equals("")){
            username.setText(" Enter the username");
        }
    }//GEN-LAST:event_usernameFocusLost

    private void show_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_passwordActionPerformed
        // TODO add your handling code here:
        if (show_password.isSelected()) {
        password_field.setEchoChar((char)0); // show text
    } else {
        password_field.setEchoChar('*');     // hide text
      
    }
    }//GEN-LAST:event_show_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateAccountButton;
    private javax.swing.JButton ForgotPasswordButton;
    private javax.swing.JLabel Login;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JCheckBox show_password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    public void LoginButtonListener(ActionListener listener){     //Same button name cannot be so we wrote LoginButtonListener written!
        LoginButton.addActionListener(listener);
    }
    public void CreateAccountButtonListener(ActionListener listener){
        CreateAccountButton.addActionListener(listener);
    }
    public void ForgotPasswordButtonListener(ActionListener listener){
        ForgotPasswordButton.addActionListener(listener);
    }
    public javax.swing.JPasswordField getPasswordField(){           // textfield bata user ko input linu paryo teslai store garnu paryo haina!
        return password_field;                                        // jun return garirako yesko name ko sanga milnu paryo variable sanga milnu paryo tya mathi (private javax.swing.JTextField password;) yo sanga milnu paryo
    }
    public javax.swing.JTextField getUsernameField(){
        return username;
    }

    public JButton getLoginButton() {
         return LoginButton;
    }

    public JButton getForgotPasswordButton() {
        return ForgotPasswordButton;
    }

    public JButton getCreateAccountButton() {
        return CreateAccountButton;
    }

}
