
package view;

import dao.DeckDao;
import model.UserModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import view.Dashtwo;

public class NewDeckDialog extends javax.swing.JDialog {

    private static final Logger logger = Logger.getLogger(NewDeckDialog.class.getName());
    private UserModel currentUser;
    private boolean okPressed;
    private int createdDeckId = -1;   // will hold the new deck's ID
    private Dashtwo dash;
    private boolean deckCreated;
    private String createdDeckName;


    // ✅ Constructor with UserModel
    public NewDeckDialog(java.awt.Frame parent, boolean modal, UserModel user) {
    super(parent, modal);
    this.currentUser = user;
    this.dash = (Dashtwo) parent;   // ✅ keep reference to dashboard
    initComponents();
    CreateNewDeck_Button.addActionListener(evt -> saveDeck());

    pack();                 // ✅ fit to design size
    setResizable(false);    // ✅ prevent resizing
    setLocationRelativeTo(parent); // ✅ keep centered
    }

    // ✅ Save deck method
    private void saveDeck() {
    String deckName = deck_name.getText().trim();

    if (deckName.isEmpty() || deckName.equals("Deck name")) {
        JOptionPane.showMessageDialog(this, "Please enter a valid deck name.");
        return;
    }

    try {
        DeckDao DeckDao = new DeckDao();
        int deckId = DeckDao.addDeck(currentUser.getUserId(), deckName);

        if (deckId != -1) {
            JOptionPane.showMessageDialog(this, "Deck '" + deckName + "' saved successfully!");

            // ✅ store results for controller
            createdDeckId = deckId;
            createdDeckName = deckName;
            deckCreated = true;
            okPressed = true;

            dispose(); // close dialog
        } else {
            JOptionPane.showMessageDialog(this, "Error saving deck. Please try again.");
        }
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error saving deck: " + ex.getMessage());
    }
}

        public int getCreatedDeckId() {
        return createdDeckId;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deck_name = new javax.swing.JTextField();
        CreateNewDeck_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 330));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("New Deck");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(152, 30, 89, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("<html><b>Create your own deck.</b><font color=\"#888888\">You get the best results from<br>the cards you create yourself.</html>");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(31, 78, 355, 53);

        deck_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deck_name.setForeground(new java.awt.Color(153, 153, 153));
        deck_name.setText("Deck name");
        deck_name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deck_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deck_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                deck_nameFocusLost(evt);
            }
        });
        getContentPane().add(deck_name);
        deck_name.setBounds(31, 161, 324, 41);

        CreateNewDeck_Button.setBackground(new java.awt.Color(0, 153, 255));
        CreateNewDeck_Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CreateNewDeck_Button.setForeground(new java.awt.Color(255, 255, 255));
        CreateNewDeck_Button.setText("Create new deck");
        CreateNewDeck_Button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CreateNewDeck_Button.addActionListener(this::CreateNewDeck_ButtonActionPerformed);
        getContentPane().add(CreateNewDeck_Button);
        CreateNewDeck_Button.setBounds(31, 220, 324, 41);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deck_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deck_nameFocusGained
        // TODO add your handling code here:
        if(deck_name.getText().equals("Deck name")){
            deck_name.setText("");
        }
    }//GEN-LAST:event_deck_nameFocusGained

    private void deck_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deck_nameFocusLost
        // TODO add your handling code here:
        if(deck_name.getText().equals("")){
            deck_name.setText("Deck name");
        }
    }//GEN-LAST:event_deck_nameFocusLost

    private void CreateNewDeck_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewDeck_ButtonActionPerformed
        // TODO add your handling code here:
    

    }//GEN-LAST:event_CreateNewDeck_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(() -> {
        // ✅ Use a dummy user for testing
        model.UserModel dummyUser = new model.UserModel(1, "testuser", "password");
        NewDeckDialog dialog = new NewDeckDialog(new javax.swing.JFrame(), true, dummyUser);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
        dialog.setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateNewDeck_Button;
    private javax.swing.JTextField deck_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    public boolean isOkPressed() {
        return okPressed;
    }

    public String getDeckName() {
        return deck_name.getText();
    }

    public boolean isDeckCreated() {
        return deckCreated;    }

    public String getCreatedDeckName() {
        return createdDeckName;    }
    
    
    
    
}
