/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


import controller.UserController;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPasswordField;

/**
 *
 * @author LENOVO
 */
public class Signup extends javax.swing.JFrame {
    
      private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Signup.class.getName());

      
    public Signup() {
        initComponents();
        setSize(1285,760);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username_Text_Field = new javax.swing.JTextField();
        Login_Button = new javax.swing.JButton();
        Signup_Title = new javax.swing.JLabel();
        Signup_Button = new javax.swing.JButton();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Confirm_password = new javax.swing.JLabel();
        Flashcard_Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        show_confirm_password = new javax.swing.JCheckBox();
        Password_Field = new javax.swing.JPasswordField();
        Confirm_Password_Field = new javax.swing.JPasswordField();
        show_password = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        username_Text_Field.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        username_Text_Field.setForeground(new java.awt.Color(51, 51, 51));
        username_Text_Field.setText(" Enter the username");
        username_Text_Field.setBorder(null);
        username_Text_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_Text_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                username_Text_FieldFocusLost(evt);
            }
        });
        username_Text_Field.addActionListener(this::username_Text_FieldActionPerformed);
        getContentPane().add(username_Text_Field);
        username_Text_Field.setBounds(20, 180, 310, 40);

        Login_Button.setBackground(new java.awt.Color(23, 150, 255));
        Login_Button.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Login_Button.setForeground(new java.awt.Color(255, 255, 255));
        Login_Button.setText("Login");
        Login_Button.setBorder(null);
        Login_Button.addActionListener(this::Login_ButtonActionPerformed);
        getContentPane().add(Login_Button);
        Login_Button.setBounds(80, 630, 90, 40);

        Signup_Title.setBackground(new java.awt.Color(26, 98, 169));
        Signup_Title.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        Signup_Title.setForeground(new java.awt.Color(255, 255, 255));
        Signup_Title.setText("SIGN UP");
        getContentPane().add(Signup_Title);
        Signup_Title.setBounds(140, 30, 210, 63);

        Signup_Button.setBackground(new java.awt.Color(23, 150, 255));
        Signup_Button.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Signup_Button.setForeground(new java.awt.Color(255, 255, 255));
        Signup_Button.setText("Signup");
        Signup_Button.setBorder(null);
        getContentPane().add(Signup_Button);
        Signup_Button.setBounds(180, 630, 90, 40);

        Username.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username");
        getContentPane().add(Username);
        Username.setBounds(20, 150, 90, 22);

        Password.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        getContentPane().add(Password);
        Password.setBounds(20, 300, 80, 22);

        Confirm_password.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Confirm_password.setForeground(new java.awt.Color(255, 255, 255));
        Confirm_password.setText("Confirm password");
        getContentPane().add(Confirm_password);
        Confirm_password.setBounds(20, 450, 150, 22);

        Flashcard_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signupp.png"))); // NOI18N
        Flashcard_Logo.setText("jLabel6");
        getContentPane().add(Flashcard_Logo);
        Flashcard_Logo.setBounds(-30, 10, 170, 150);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 65)); // NOI18N
        jLabel1.setText("Flashcard Study ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(570, 270, 540, 120);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 45)); // NOI18N
        jLabel4.setText("Learn More, Stress Less");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(570, 350, 570, 71);

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        jLabel5.setText("Create flashcards and crush exams, with the magic of spaced");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(560, 420, 560, 40);

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel10.setText("Heart");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(470, 0, 120, 60);

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel9.setText("What is the area of circle?");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1070, 150, 160, 30);

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        jLabel6.setText("repetetion. Join our community of smart learners.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(610, 440, 490, 40);

        jLabel17.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel17.setText("Name the flag");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(1130, 500, 90, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (31).png"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1060, 20, 170, 200);

        jLabel15.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel15.setText("Computer parts");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(420, 500, 110, 40);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (37).png"))); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        getContentPane().add(jLabel16);
        jLabel16.setBounds(1080, 510, 170, 200);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (38).png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1050, 520, 200, 190);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (30).png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jLabel2.setMaximumSize(new java.awt.Dimension(170, 200));
        jLabel2.setMinimumSize(new java.awt.Dimension(170, 200));
        jLabel2.setPreferredSize(new java.awt.Dimension(170, 200));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 20, 170, 200);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (26).png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(370, 30, 170, 200);

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setForeground(new java.awt.Color(232, 232, 232));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (34).png"))); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(380, 510, 170, 200);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (35).png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(400, 520, 170, 200);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (32).png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1090, -10, 250, 260);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image 162 (3).png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(470, 150, 671, 410);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(1050, 220, 116, 20);

        show_confirm_password.setBackground(new java.awt.Color(30, 98, 165));
        show_confirm_password.setForeground(new java.awt.Color(255, 255, 255));
        show_confirm_password.setText("Show confirm password");
        show_confirm_password.setBorder(null);
        show_confirm_password.addActionListener(this::show_confirm_passwordActionPerformed);
        getContentPane().add(show_confirm_password);
        show_confirm_password.setBounds(170, 530, 170, 18);

        Password_Field.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        Password_Field.setForeground(new java.awt.Color(51, 51, 51));
        Password_Field.setBorder(null);
        getContentPane().add(Password_Field);
        Password_Field.setBounds(20, 330, 310, 40);

        Confirm_Password_Field.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        Confirm_Password_Field.setForeground(new java.awt.Color(51, 51, 51));
        Confirm_Password_Field.setBorder(null);
        getContentPane().add(Confirm_Password_Field);
        Confirm_Password_Field.setBounds(20, 480, 310, 40);

        show_password.setBackground(new java.awt.Color(30, 98, 165));
        show_password.setForeground(new java.awt.Color(255, 255, 255));
        show_password.setText("Show password");
        show_password.setBorder(null);
        show_password.addActionListener(this::show_passwordActionPerformed);
        getContentPane().add(show_password);
        show_password.setBounds(212, 380, 120, 18);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(350, -110, 940, 860);

        jPanel1.setBackground(new java.awt.Color(30, 98, 165));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 350, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_Text_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_Text_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_Text_FieldActionPerformed

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
        // TODO add your handling code here:
        Login loginView = new Login();
        controller.LoginController lc = new controller.LoginController(loginView);
        lc.open();
        this.dispose();


    }//GEN-LAST:event_Login_ButtonActionPerformed

    private void username_Text_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_Text_FieldFocusGained
        // TODO add your handling code here:
        if(username_Text_Field.getText().equals(" Enter the username")){
            username_Text_Field.setText("");
        }
    }//GEN-LAST:event_username_Text_FieldFocusGained

    private void username_Text_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_Text_FieldFocusLost
        // TODO add your handling code here:
        if(username_Text_Field.getText().equals("")){
            username_Text_Field.setText(" Enter the username");
        }
    }//GEN-LAST:event_username_Text_FieldFocusLost

    private void show_confirm_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_confirm_passwordActionPerformed
        // TODO add your handling code here:
             if (show_confirm_password.isSelected()) {
        Confirm_Password_Field.setEchoChar((char)0); // show text
    } else {
        Confirm_Password_Field.setEchoChar('*');     // hide text
    }
    }//GEN-LAST:event_show_confirm_passwordActionPerformed

    private void show_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_passwordActionPerformed
        // TODO add your handling code here:
        if (show_password.isSelected()) {
        Password_Field.setEchoChar((char)0); // show text
    } else {
        Password_Field.setEchoChar('*');     // hide text
      
    }


    }//GEN-LAST:event_show_passwordActionPerformed

    /**
     * @param args
     */
 public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        Signup view = new Signup();               // Create only ONE Signup view
        UserController controller = new UserController(view); // Attach controller
        view.setVisible(true);                    // Show the same view
    });
}

   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Confirm_Password_Field;
    private javax.swing.JLabel Confirm_password;
    private javax.swing.JLabel Flashcard_Logo;
    private javax.swing.JButton Login_Button;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField Password_Field;
    private javax.swing.JButton Signup_Button;
    private javax.swing.JLabel Signup_Title;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JCheckBox show_confirm_password;
    private javax.swing.JCheckBox show_password;
    private javax.swing.JTextField username_Text_Field;
    // End of variables declaration//GEN-END:variables

    public void AddUserListener(ActionListener listener){
    Signup_Button.addActionListener(listener);
    }
    public void LoginButtonListener(ActionListener listener){
        Login_Button.addActionListener(listener);
    }
    public javax.swing.JPasswordField getPasswordField(){
        return Password_Field; 
    }
    public javax.swing.JPasswordField getConfirmPasswordField(){
        return Confirm_Password_Field; 
    }
    public javax.swing.JTextField getUsernameField(){
        return username_Text_Field; 
    }
}





