/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author LENOVO
 */
public class Signup extends javax.swing.JFrame {
    
      private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Signup.class.getName());

    

    public Signup() {
        initComponents();
        setSize(1285,760);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username_Text_Field = new javax.swing.JTextField();
        password_Text_Field = new javax.swing.JTextField();
        Login_Button = new javax.swing.JButton();
        Signup_Title = new javax.swing.JLabel();
        Signup_Button = new javax.swing.JButton();
        confirm_password_Text_Field = new javax.swing.JTextField();
        Username = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Confirm_password = new javax.swing.JLabel();
        Flashcard_Logo = new javax.swing.JLabel();
        email_Text_Field = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1285, 760));
        getContentPane().setLayout(null);

        username_Text_Field.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        username_Text_Field.setForeground(new java.awt.Color(153, 153, 153));
        username_Text_Field.setText(" Enter the username");
        username_Text_Field.setBorder(null);
        username_Text_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_Text_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                username_Text_FieldFocusLost(evt);
            }
        });
        username_Text_Field.addActionListener(this::username_Text_FieldActionPerformed);
        getContentPane().add(username_Text_Field);
        username_Text_Field.setBounds(20, 180, 310, 40);

        password_Text_Field.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        password_Text_Field.setForeground(new java.awt.Color(153, 153, 153));
        password_Text_Field.setText(" Enter the password");
        password_Text_Field.setBorder(null);
        password_Text_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_Text_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password_Text_FieldFocusLost(evt);
            }
        });
        password_Text_Field.addActionListener(this::password_Text_FieldActionPerformed);
        getContentPane().add(password_Text_Field);
        password_Text_Field.setBounds(20, 430, 310, 40);

        Login_Button.setBackground(new java.awt.Color(23, 150, 255));
        Login_Button.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Login_Button.setForeground(new java.awt.Color(255, 255, 255));
        Login_Button.setText("Login");
        Login_Button.setBorder(null);
        Login_Button.addActionListener(this::Login_ButtonActionPerformed);
        getContentPane().add(Login_Button);
        Login_Button.setBounds(50, 660, 90, 40);

        Signup_Title.setBackground(new java.awt.Color(26, 98, 169));
        Signup_Title.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        Signup_Title.setForeground(new java.awt.Color(255, 255, 255));
        Signup_Title.setText("SIGN UP");
        getContentPane().add(Signup_Title);
        Signup_Title.setBounds(140, 30, 210, 63);

        Signup_Button.setBackground(new java.awt.Color(23, 150, 255));
        Signup_Button.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Signup_Button.setForeground(new java.awt.Color(255, 255, 255));
        Signup_Button.setText("Signup");
        Signup_Button.setBorder(null);
        getContentPane().add(Signup_Button);
        Signup_Button.setBounds(160, 660, 90, 40);

        confirm_password_Text_Field.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        confirm_password_Text_Field.setForeground(new java.awt.Color(153, 153, 153));
        confirm_password_Text_Field.setText(" Re-type to confirm password");
        confirm_password_Text_Field.setBorder(null);
        confirm_password_Text_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirm_password_Text_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirm_password_Text_FieldFocusLost(evt);
            }
        });
        confirm_password_Text_Field.addActionListener(this::confirm_password_Text_FieldActionPerformed);
        getContentPane().add(confirm_password_Text_Field);
        confirm_password_Text_Field.setBounds(20, 550, 310, 40);

        Username.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username");
        getContentPane().add(Username);
        Username.setBounds(20, 150, 90, 22);

        Email.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email");
        getContentPane().add(Email);
        Email.setBounds(20, 280, 50, 22);

        Password.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        getContentPane().add(Password);
        Password.setBounds(20, 400, 80, 22);

        Confirm_password.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Confirm_password.setForeground(new java.awt.Color(255, 255, 255));
        Confirm_password.setText("Confirm password");
        getContentPane().add(Confirm_password);
        Confirm_password.setBounds(20, 520, 150, 22);

        Flashcard_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signupp.png"))); // NOI18N
        Flashcard_Logo.setText("jLabel6");
        getContentPane().add(Flashcard_Logo);
        Flashcard_Logo.setBounds(-30, 10, 170, 150);

        email_Text_Field.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        email_Text_Field.setForeground(new java.awt.Color(153, 153, 153));
        email_Text_Field.setText(" Enter the email");
        email_Text_Field.setBorder(null);
        email_Text_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                email_Text_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                email_Text_FieldFocusLost(evt);
            }
        });
        email_Text_Field.addActionListener(this::email_Text_FieldActionPerformed);
        getContentPane().add(email_Text_Field);
        email_Text_Field.setBounds(20, 310, 310, 40);

        jPanel1.setBackground(new java.awt.Color(30, 98, 165));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 350, 760);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangle 2887.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 150, 740, 480);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(430, 40, 160, 210);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(690, 80, 37, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_Text_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_Text_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_Text_FieldActionPerformed

    private void password_Text_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_Text_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_Text_FieldActionPerformed

    private void confirm_password_Text_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_password_Text_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirm_password_Text_FieldActionPerformed

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login_ButtonActionPerformed

    private void username_Text_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_Text_FieldFocusGained
        // TODO add your handling code here:
        if(username_Text_Field.getText().equals(" Enter the username")){
            username_Text_Field.setText("");
        }
    }//GEN-LAST:event_username_Text_FieldFocusGained

    private void username_Text_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_Text_FieldFocusLost
        // TODO add your handling code here:
        if(username_Text_Field.getText().equals("")){
            username_Text_Field.setText(" Enter the username");
        }
    }//GEN-LAST:event_username_Text_FieldFocusLost

    private void password_Text_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_Text_FieldFocusGained
        // TODO add your handling code here:
        if(password_Text_Field.getText().equals(" Enter the password")){
            password_Text_Field.setText("");
        }
    }//GEN-LAST:event_password_Text_FieldFocusGained

    private void password_Text_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_Text_FieldFocusLost
        // TODO add your handling code here:
        if(password_Text_Field.getText().equals("")){
            password_Text_Field.setText(" Enter the password");
        }
    }//GEN-LAST:event_password_Text_FieldFocusLost

    private void confirm_password_Text_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirm_password_Text_FieldFocusGained
        // TODO add your handling code here:
        if(confirm_password_Text_Field.getText().equals(" Re-type to confirm password")){
            confirm_password_Text_Field.setText("");
    }      
    }//GEN-LAST:event_confirm_password_Text_FieldFocusGained

    private void confirm_password_Text_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirm_password_Text_FieldFocusLost
        // TODO add your handling code here:
        if(password_Text_Field.getText().equals("")){
            password_Text_Field.setText(" Re-type to confirm password");
        }
    }//GEN-LAST:event_confirm_password_Text_FieldFocusLost

    private void email_Text_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_Text_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_Text_FieldActionPerformed

    private void email_Text_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_Text_FieldFocusGained
        // TODO add your handling code here:
        if(email_Text_Field.getText().equals(" Enter the email")){
            email_Text_Field.setText("");
    }     
    }//GEN-LAST:event_email_Text_FieldFocusGained

    private void email_Text_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_Text_FieldFocusLost
        // TODO add your handling code here:
        if(email_Text_Field.getText().equals("")){
            email_Text_Field.setText(" Enter the email");
        }
    }//GEN-LAST:event_email_Text_FieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Signup().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Confirm_password;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Flashcard_Logo;
    private javax.swing.JButton Login_Button;
    private javax.swing.JLabel Password;
    private javax.swing.JButton Signup_Button;
    private javax.swing.JLabel Signup_Title;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField confirm_password_Text_Field;
    private javax.swing.JTextField email_Text_Field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField password_Text_Field;
    private javax.swing.JTextField username_Text_Field;
    // End of variables declaration//GEN-END:variables

    public void AddUserListener(ActionListener listener){
        Signup_Button.addActionListener(listener);
    }
    public void LoginButtonListener(ActionListener listener){
        Login_Button.addActionListener(listener);
    }
    public javax.swing.JTextField getPasswordField(){
        return password_Text_Field; 
    }
    public javax.swing.JTextField getConfirmPasswordField(){
        return confirm_password_Text_Field; 
    }
    public javax.swing.JTextField getEmailField(){
        return email_Text_Field; 
    }
    public javax.swing.JTextField getUsernameField(){
        return username_Text_Field; 
    }
}
