/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;            // we are importing event



/**
 *
 * @author LENOVO
 */
public class Signup extends javax.swing.JFrame {                
private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Signup.class.getName());

    public Signup() {
        initComponents();
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginbtnDemo = new javax.swing.JButton();
        signupBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ConfirmPassword = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        confirmpassword = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        Username = new javax.swing.JLabel();
        SIGNUPNOW = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1285, 760));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginbtnDemo.setBackground(new java.awt.Color(33, 151, 255));
        loginbtnDemo.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        loginbtnDemo.setForeground(new java.awt.Color(255, 255, 255));
        loginbtnDemo.setText("Login");
        loginbtnDemo.setBorder(null);
        loginbtnDemo.addActionListener(this::loginbtnDemoActionPerformed);
        getContentPane().add(loginbtnDemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, 110, 40));

        signupBtn.setBackground(new java.awt.Color(0, 153, 255));
        signupBtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        signupBtn.setForeground(new java.awt.Color(255, 255, 255));
        signupBtn.setText("Signup ");
        signupBtn.setBorder(null);
        signupBtn.addActionListener(this::signupBtnActionPerformed);
        getContentPane().add(signupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 670, 110, 40));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, -1, -1));

        ConfirmPassword.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        ConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmPassword.setText("Confirm password");
        getContentPane().add(ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 200, 30));

        username.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(153, 153, 153));
        username.setText("  Enter the username");
        username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(this::usernameActionPerformed);
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 300, 50));

        confirmpassword.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        confirmpassword.setForeground(new java.awt.Color(153, 153, 153));
        confirmpassword.setText("  Re-type password to confirm");
        confirmpassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        confirmpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmpasswordFocusLost(evt);
            }
        });
        confirmpassword.addActionListener(this::confirmpasswordActionPerformed);
        getContentPane().add(confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 300, 50));

        Password.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 120, 30));

        Email.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 90, 30));

        emailText.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        emailText.setForeground(new java.awt.Color(153, 153, 153));
        emailText.setText("  Enter the email");
        emailText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        emailText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextFocusLost(evt);
            }
        });
        emailText.addActionListener(this::emailTextActionPerformed);
        getContentPane().add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 300, 50));

        password.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(153, 153, 153));
        password.setText("  Enter the password");
        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addActionListener(this::passwordActionPerformed);
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 300, 50));

        Username.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username");
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, 30));

        SIGNUPNOW.setFont(new java.awt.Font("Cambria", 0, 48)); // NOI18N
        SIGNUPNOW.setForeground(new java.awt.Color(255, 255, 255));
        SIGNUPNOW.setText("SIGN UP");
        getContentPane().add(SIGNUPNOW, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 190, 80));

        jPanel1.setBackground(new java.awt.Color(24, 97, 171));
        jPanel1.setForeground(new java.awt.Color(242, 242, 242));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/signupp.png"))); // NOI18N
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.setPreferredSize(new java.awt.Dimension(68, 56));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 170, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void confirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpasswordActionPerformed

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signupBtnActionPerformed

    private void loginbtnDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnDemoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginbtnDemoActionPerformed

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        // TODO add your handling code here:
        if(username.getText().equals("  Enter the username")){
            username.setText("");
        }
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
        if(username.getText().equals("")){
            username.setText("  Enter the username");
    }//GEN-LAST:event_usernameFocusLost
    }
    private void confirmpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmpasswordFocusGained
        // TODO add your handling code here:
        if(confirmpassword.getText().equals("  Re-type password to confirm")){
            confirmpassword.setText("");
    }    
    }//GEN-LAST:event_confirmpasswordFocusGained

    private void confirmpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmpasswordFocusLost
        // TODO add your handling code here:
        if(confirmpassword.getText().equals("")){
            confirmpassword.setText("  Re-type password to confirm");
    }
    }//GEN-LAST:event_confirmpasswordFocusLost

    private void emailTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFocusGained
        // TODO add your handling code here:
        if(emailText.getText().equals("  Enter the email")){
            emailText.setText("");
    }
    }//GEN-LAST:event_emailTextFocusGained

    private void emailTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFocusLost
        // TODO add your handling code here:
        if(emailText.getText().equals("")){
            emailText.setText("  Enter the email");
    }
    }//GEN-LAST:event_emailTextFocusLost

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        if(password.getText().equals("  Enter the password")){
            password.setText("");
    }
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        // TODO add your handling code here:
        if(password.getText().equals("")){
            password.setText("  Enter the password");
    }
    }//GEN-LAST:event_passwordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
                java.awt.EventQueue.invokeLater(() -> new Signup().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConfirmPassword;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel SIGNUPNOW;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField confirmpassword;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbtnDemo;
    private javax.swing.JTextField password;
    private javax.swing.JButton signupBtn;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
    
    public void AddUserListener(ActionListener listener){
        signupBtn.addActionListener(listener);
    }
    public void LoginButtonListener(ActionListener listener){     //Same button name cannot be so we wrote LoginButtonListener written!
        loginbtnDemo.addActionListener(listener);
    }
    public javax.swing.JTextField getPasswordField(){           // textfield bata user ko input linu paryo teslai store garnu paryo haina!
        return password;                                        // jun return garirako yesko name ko sanga milnu paryo variable sanga milnu paryo tya mathi (private javax.swing.JTextField password;) yo sanga milnu paryo
    }
    public javax.swing.JTextField getConfirmPasswordField(){
        return confirmpassword;
    }
    public javax.swing.JTextField getEmailField(){              // javax.swing.JTextField because user ko input store garnu ko lagi. So tesko lagi get method banako. Yo hamileh controller ma use garcha. 
        return emailText;
    }
    public javax.swing.JTextField getUsernameField(){
        return username;
    }
}

//database--> mysqlconnection --> usermodel --> userdao bata --> tesbata signup bata activate garcha--> tya bata hami controller ma jancham ani tespachi save huncha