/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author bipin ranabhat
 */
public class StudyHistory extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudyHistory.class.getName());

    /**
     * Creates new form StudyHistory
     */
    public StudyHistory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel1 = new javax.swing.JPanel();
        Logo_label = new javax.swing.JLabel();
        Library_Button1 = new javax.swing.JButton();
        Library_Button2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Home_Label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        topPanel1.setBackground(new java.awt.Color(255, 255, 255));
        topPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        topPanel1.setLayout(null);

        Logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        topPanel1.add(Logo_label);
        Logo_label.setBounds(100, 10, 60, 50);

        Library_Button1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        Library_Button1.setText("Home");
        Library_Button1.setBorder(null);
        Library_Button1.addActionListener(this::Library_Button1ActionPerformed);
        topPanel1.add(Library_Button1);
        Library_Button1.setBounds(180, 20, 90, 40);

        Library_Button2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        Library_Button2.setText("Library");
        Library_Button2.setBorder(null);
        Library_Button2.addActionListener(this::Library_Button2ActionPerformed);
        topPanel1.add(Library_Button2);
        Library_Button2.setBounds(290, 20, 90, 40);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\bipin ranabhat\\OneDrive\\Documents\\img\\acc.png")); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(this::jButton2ActionPerformed);
        topPanel1.add(jButton2);
        jButton2.setBounds(1150, 10, 60, 56);

        getContentPane().add(topPanel1);
        topPanel1.setBounds(0, 0, 1336, 70);

        Home_Label.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Home_Label.setText("Home");
        getContentPane().add(Home_Label);
        Home_Label.setBounds(106, 90, 112, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("STUDY HISTORY");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(74, 45, 203, 28);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(106, 170, 1100, 360);

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\bipin ranabhat\\OneDrive\\Documents\\img\\background .png")); // NOI18N
        Background.setText("jLabel2");
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1340, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Library_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Library_Button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Library_Button1ActionPerformed

    private void Library_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Library_Button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Library_Button2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudyHistory().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Home_Label;
    private javax.swing.JButton Library_Button1;
    private javax.swing.JButton Library_Button2;
    private javax.swing.JLabel Logo_label;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel topPanel1;
    // End of variables declaration//GEN-END:variables
}
