/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.FlashcardDao;
import java.awt.CardLayout;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import model.UserModel;

/**
 *
 * @author pranishabhatta
 */
public class Studycards2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Studycards2.class.getName());
    private Dashtwo dash;
    private UserModel currentUser;
    private int currentDeckId;
    private String currentDeckName;
   
    /**
     * Creates new form Studycards2
     */
    public Studycards2() {
        initComponents();
        setSize(1285, 760);
        
    }

public Studycards2(int deckId, String deckName, UserModel currentUser) {
        initComponents();   // ✅ must be called
        setTitle("Study Cards - " + deckName);
        setSize(1285, 760);  // ✅ give it a size
        setLocationRelativeTo(null); // ✅ center on screen
    }

    public Studycards2(Dashtwo dash, UserModel user) {
        this.dash = dash;   // 🔑 keep reference
        this.currentUser = user;
        initComponents();
    }

    public void loadDeck(int deckId, String deckName) {
        this.currentDeckId = deckId;
        this.currentDeckName = deckName;

        // Example: show deck name in a label
        NewDeckName.setText("Deck: " + deckName);

        // TODO: load cards from database or file using deckId
        // e.g. CardDao dao = new CardDao();
        // List<Card> cards = dao.getCardsForDeck(deckId);
        // populateCards(cards);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        AddCardsButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        topPanel1 = new javax.swing.JPanel();
        Home_Button = new javax.swing.JButton();
        Logo_label = new javax.swing.JLabel();
        Library_Button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        tickButton = new javax.swing.JButton();
        NewDeckName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        AddNumberOfCardsCreated = new javax.swing.JTextField();
        StudyCardsButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1285, 760));
        getContentPane().setLayout(null);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        jTextField6.setBorder(null);
        jPanel6.add(jTextField6);
        jTextField6.setBounds(6, 17, 184, 16);

        jTextField7.setBorder(null);
        jPanel6.add(jTextField7);
        jTextField7.setBounds(6, 39, 143, 16);

        AddCardsButton.setBackground(new java.awt.Color(0, 0, 0));
        AddCardsButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AddCardsButton.setForeground(new java.awt.Color(255, 255, 255));
        AddCardsButton.setText("Add cards");
        AddCardsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCardsButtonActionPerformed(evt);
            }
        });
        jPanel6.add(AddCardsButton);
        AddCardsButton.setBounds(430, 17, 210, 36);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(100, 580, 1090, 80);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setText("Filters");
        getContentPane().add(jButton3);
        jButton3.setBounds(1102, 540, 90, 30);

        topPanel1.setBackground(new java.awt.Color(255, 255, 255));
        topPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        topPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home_Button.setBackground(new java.awt.Color(254, 254, 254));
        Home_Button.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        Home_Button.setText("Home");
        Home_Button.setBorder(null);
        Home_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_ButtonActionPerformed(evt);
            }
        });
        topPanel1.add(Home_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 21, 60, 20));

        Logo_label.setBackground(new java.awt.Color(254, 254, 254));
        Logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/122.png"))); // NOI18N
        topPanel1.add(Logo_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 1, 80, -1));

        Library_Button.setBackground(new java.awt.Color(254, 254, 254));
        Library_Button.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        Library_Button.setText("Library");
        Library_Button.setBorder(null);
        topPanel1.add(Library_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 11, 70, 40));

        jLabel4.setBackground(new java.awt.Color(254, 254, 254));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/13.png"))); // NOI18N
        topPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1123, 1, -1, 65));

        getContentPane().add(topPanel1);
        topPanel1.setBounds(0, 0, 1380, 70);

        NextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arr.png"))); // NOI18N
        NextButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NextButton);
        NextButton.setBounds(100, 90, 30, 30);

        tickButton.setBackground(new java.awt.Color(0, 153, 255));
        tickButton.setForeground(new java.awt.Color(255, 255, 255));
        tickButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tick1.png"))); // NOI18N
        tickButton.setBorder(null);
        tickButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tickButtonActionPerformed(evt);
            }
        });
        getContentPane().add(tickButton);
        tickButton.setBounds(1110, 100, 70, 40);

        NewDeckName.setBackground(new java.awt.Color(240, 240, 240));
        NewDeckName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        NewDeckName.setBorder(null);
        getContentPane().add(NewDeckName);
        NewDeckName.setBounds(150, 90, 940, 30);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Learning algorithm: Spaced repetition");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 140, 280, 19);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel4.setLayout(null);

        AddNumberOfCardsCreated.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        AddNumberOfCardsCreated.setBorder(null);
        AddNumberOfCardsCreated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNumberOfCardsCreatedActionPerformed(evt);
            }
        });
        jPanel4.add(AddNumberOfCardsCreated);
        AddNumberOfCardsCreated.setBounds(600, 70, 350, 60);

        StudyCardsButton.setBackground(new java.awt.Color(0, 153, 255));
        StudyCardsButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        StudyCardsButton.setForeground(new java.awt.Color(255, 255, 255));
        StudyCardsButton.setText("Study cards");
        jPanel4.add(StudyCardsButton);
        StudyCardsButton.setBounds(20, 190, 1020, 40);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Cards in deck =");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(420, 80, 180, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(100, 198, 1090, 250);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Search cards");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(888, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        getContentPane().add(jPanel9);
        jPanel9.setBounds(98, 475, 1090, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_ButtonActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_Home_ButtonActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NextButtonActionPerformed

    private void tickButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tickButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tickButtonActionPerformed

    private void AddNumberOfCardsCreatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNumberOfCardsCreatedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddNumberOfCardsCreatedActionPerformed

    private void AddCardsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCardsButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AddCardsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Studycards2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCardsButton;
    private javax.swing.JTextField AddNumberOfCardsCreated;
    private javax.swing.JButton Home_Button;
    private javax.swing.JButton Library_Button;
    private javax.swing.JLabel Logo_label;
    private javax.swing.JTextField NewDeckName;
    private javax.swing.JButton NextButton;
    private javax.swing.JButton StudyCardsButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JButton tickButton;
    private javax.swing.JPanel topPanel1;
    // End of variables declaration//GEN-END:variables
// Listener registration
    public void addAddCardsButtonListener(ActionListener listener) {
        AddCardsButton.addActionListener(listener);
    }
    public void StudyCardsButtonListener(ActionListener listener) {
        StudyCardsButton.addActionListener(listener);
    }
    
    // Getter for deck title label
    public JTextField getDeckNameField() {
        return NewDeckName;
    }
    public void HomeButtonListener(ActionListener listener){
    Home_Button.addActionListener(listener);
    }
    public void NextButtonListener(ActionListener listener){
    NextButton.addActionListener(listener);
    }

    public JTextField getNumberOfCardsCreatedField() {
    return AddNumberOfCardsCreated; // make sure this text field exists in your form
    }

    public void updateCardCount(int deckId, int userId) {
    // Use DAO to get the count from DB
    FlashcardDao dao = new FlashcardDao();
    int count = dao.getFlashcardCount(deckId, userId);

    // ✅ Update the label/text field in Studycards2
    AddNumberOfCardsCreated.setText("Cards: " + count);
}
    
}
