package view;

import model.UserModel;
import view.Dashtwo;

public class UserBasedFlashcardOwnership extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(UserBasedFlashcardOwnership.class.getName());

    // ✅ Add this field to store the logged-in user
    private final UserModel currentUser;

    /** No-arg constructor (used by GUI builder or fallback) */
    public UserBasedFlashcardOwnership() {
        initComponents();
        setSize(1285, 760);
        this.currentUser = null; // fallback
    }

    /** Preferred constructor with user context */
    public UserBasedFlashcardOwnership(UserModel user) {
        initComponents();
        setSize(1285, 760);
        this.currentUser = user;

        // ✅ Populate fields with user info
        Username_Text_Field.setText(user.getUsername());
        UserID_Text_Field.setText(String.valueOf(user.getUserId()));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerpanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Edit_Profile_Button = new javax.swing.JButton();
        Username_Text_Field = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        update_password_Text_Field = new javax.swing.JTextField();
        Copy_Button = new javax.swing.JButton();
        UserID_Text_Field = new javax.swing.JTextField();
        ID_Label = new javax.swing.JLabel();
        topPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Home_Button = new javax.swing.JButton();
        Library_Button = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Save_Button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        centerpanel.setBackground(new java.awt.Color(255, 255, 255));
        centerpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        centerpanel.setLayout(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        centerpanel.add(jPanel5);
        jPanel5.setBounds(120, 230, 0, 0);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        centerpanel.add(jPanel8);
        jPanel8.setBounds(310, 230, 0, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (39).png"))); // NOI18N
        centerpanel.add(jLabel1);
        jLabel1.setBounds(20, 10, 110, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-17 205936.png"))); // NOI18N
        centerpanel.add(jLabel4);
        jLabel4.setBounds(870, 0, 30, 60);

        Edit_Profile_Button.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Edit_Profile_Button.setText("       Edit public profile");
        Edit_Profile_Button.addActionListener(this::Edit_Profile_ButtonActionPerformed);
        centerpanel.add(Edit_Profile_Button);
        Edit_Profile_Button.setBounds(850, 16, 180, 30);

        Username_Text_Field.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Username_Text_Field.setBorder(null);
        Username_Text_Field.addActionListener(this::Username_Text_FieldActionPerformed);
        centerpanel.add(Username_Text_Field);
        Username_Text_Field.setBounds(130, 40, 140, 40);

        getContentPane().add(centerpanel);
        centerpanel.setBounds(119, 140, 1050, 120);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jTextField3.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setText("Password");
        jTextField3.setBorder(null);
        jTextField3.addActionListener(this::jTextField3ActionPerformed);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(30, 30, 120, 30);

        update_password_Text_Field.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        update_password_Text_Field.setText("Update password");
        update_password_Text_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                update_password_Text_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                update_password_Text_FieldFocusLost(evt);
            }
        });
        update_password_Text_Field.addActionListener(this::update_password_Text_FieldActionPerformed);
        jPanel1.add(update_password_Text_Field);
        update_password_Text_Field.setBounds(30, 60, 200, 50);

        Copy_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-17 225511.png"))); // NOI18N
        Copy_Button.setBorder(null);
        Copy_Button.addActionListener(this::Copy_ButtonActionPerformed);
        jPanel1.add(Copy_Button);
        Copy_Button.setBounds(60, 360, 40, 30);

        UserID_Text_Field.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        UserID_Text_Field.setForeground(new java.awt.Color(153, 153, 153));
        UserID_Text_Field.setBorder(null);
        UserID_Text_Field.addActionListener(this::UserID_Text_FieldActionPerformed);
        jPanel1.add(UserID_Text_Field);
        UserID_Text_Field.setBounds(40, 350, 60, 50);

        ID_Label.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        ID_Label.setForeground(new java.awt.Color(153, 153, 153));
        ID_Label.setText("ID:");
        jPanel1.add(ID_Label);
        ID_Label.setBounds(20, 366, 20, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(120, 280, 1050, 400);

        topPanel1.setBackground(new java.awt.Color(255, 255, 255));
        topPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        topPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        topPanel1.add(jLabel3);
        jLabel3.setBounds(120, 0, 60, 60);

        Home_Button.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        Home_Button.setText("Home");
        Home_Button.setBorder(null);
        Home_Button.addActionListener(this::Home_ButtonActionPerformed);
        topPanel1.add(Home_Button);
        Home_Button.setBounds(200, 10, 80, 40);

        Library_Button.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        Library_Button.setText("Library");
        Library_Button.setBorder(null);
        topPanel1.add(Library_Button);
        Library_Button.setBounds(290, 10, 80, 40);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (40).png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.addActionListener(this::jButton5ActionPerformed);
        topPanel1.add(jButton5);
        jButton5.setBounds(1120, 10, 50, 60);

        getContentPane().add(topPanel1);
        topPanel1.setBounds(0, 0, 1290, 70);

        Save_Button.setBackground(new java.awt.Color(0, 141, 237));
        Save_Button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Save_Button.setForeground(new java.awt.Color(255, 255, 255));
        Save_Button.setText("Save");
        Save_Button.addActionListener(this::Save_ButtonActionPerformed);
        getContentPane().add(Save_Button);
        Save_Button.setBounds(1100, 85, 70, 40);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Account");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 90, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_ButtonActionPerformed
        // TODO add your handling code here:
         // Open Dashtwo dashboard
        Dashtwo dashboard = new Dashtwo(currentUser); // ✅ now this works
        dashboard.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_Home_ButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void Save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Save_ButtonActionPerformed

    private void Edit_Profile_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_Profile_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Edit_Profile_ButtonActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void UserID_Text_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserID_Text_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserID_Text_FieldActionPerformed

    private void Copy_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Copy_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Copy_ButtonActionPerformed

    private void update_password_Text_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_password_Text_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_update_password_Text_FieldActionPerformed

    private void Username_Text_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_Text_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_Text_FieldActionPerformed

    private void update_password_Text_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_update_password_Text_FieldFocusGained
        // TODO add your handling code here:
        if(update_password_Text_Field.getText().equals("Update password")){
            update_password_Text_Field.setText("");
        }
    }//GEN-LAST:event_update_password_Text_FieldFocusGained

    private void update_password_Text_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_update_password_Text_FieldFocusLost
        // TODO add your handling code here:
        if(update_password_Text_Field.getText().equals("")){
            update_password_Text_Field.setText("Update password");
        }
    }//GEN-LAST:event_update_password_Text_FieldFocusLost

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new UserBasedFlashcardOwnership().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Copy_Button;
    private javax.swing.JButton Edit_Profile_Button;
    private javax.swing.JButton Home_Button;
    private javax.swing.JLabel ID_Label;
    private javax.swing.JButton Library_Button;
    private javax.swing.JButton Save_Button;
    private javax.swing.JTextField UserID_Text_Field;
    private javax.swing.JTextField Username_Text_Field;
    private javax.swing.JPanel centerpanel;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel topPanel1;
    private javax.swing.JTextField update_password_Text_Field;
    // End of variables declaration//GEN-END:variables
}
