/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

import view.Dashtwo;
/**
 *
 * @author LENOVO
 */
public class UserBasedFlashcardOwnership extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserBasedFlashcardOwnership.class.getName());
    

    /**
     * Creates new form UserBasedFlashcardOwnership
     */
    public UserBasedFlashcardOwnership() {
    initComponents();
    setSize(1285,760);

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerpanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        password_Text_Field = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        UserID_Text_Field = new javax.swing.JTextField();
        email_Text_Field = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        topPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Home_Button = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        centerpanel.setBackground(new java.awt.Color(255, 255, 255));
        centerpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        centerpanel.setLayout(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        centerpanel.add(jPanel5);
        jPanel5.setBounds(120, 230, 0, 0);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        centerpanel.add(jPanel8);
        jPanel8.setBounds(310, 230, 0, 0);

        jTextField2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setText("@useremail.com");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(this::jTextField2ActionPerformed);
        centerpanel.add(jTextField2);
        jTextField2.setBounds(120, 60, 120, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (39).png"))); // NOI18N
        centerpanel.add(jLabel1);
        jLabel1.setBounds(10, 10, 110, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-17 205936.png"))); // NOI18N
        centerpanel.add(jLabel4);
        jLabel4.setBounds(890, 0, 20, 40);

        jButton2.setText("       Edit public profile");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        centerpanel.add(jButton2);
        jButton2.setBounds(870, 10, 160, 23);

        jTextField1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jTextField1.setText("Username");
        jTextField1.setBorder(null);
        centerpanel.add(jTextField1);
        jTextField1.setBounds(120, 30, 140, 30);

        getContentPane().add(centerpanel);
        centerpanel.setBounds(119, 140, 1050, 120);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(null);

        jTextField3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setText("Password");
        jTextField3.setBorder(null);
        jTextField3.addActionListener(this::jTextField3ActionPerformed);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(590, 20, 120, 30);

        password_Text_Field.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        password_Text_Field.setText("useremail@gmail.com");
        jPanel1.add(password_Text_Field);
        password_Text_Field.setBounds(590, 50, 230, 40);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2025-12-17 225511.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.addActionListener(this::jButton6ActionPerformed);
        jPanel1.add(jButton6);
        jButton6.setBounds(70, 360, 30, 30);

        UserID_Text_Field.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        UserID_Text_Field.setForeground(new java.awt.Color(153, 153, 153));
        UserID_Text_Field.setText("ID: 01");
        UserID_Text_Field.setBorder(null);
        UserID_Text_Field.addActionListener(this::UserID_Text_FieldActionPerformed);
        jPanel1.add(UserID_Text_Field);
        UserID_Text_Field.setBounds(20, 360, 60, 30);

        email_Text_Field.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        email_Text_Field.setText("useremail@gmail.com");
        jPanel1.add(email_Text_Field);
        email_Text_Field.setBounds(20, 50, 540, 40);

        jTextField6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        jTextField6.setText("Email");
        jTextField6.setBorder(null);
        jTextField6.addActionListener(this::jTextField6ActionPerformed);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(20, 20, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(120, 280, 1050, 400);

        topPanel1.setBackground(new java.awt.Color(255, 255, 255));
        topPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        topPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        topPanel1.add(jLabel3);
        jLabel3.setBounds(120, 0, 60, 60);

        Home_Button.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Home_Button.setText("Home");
        Home_Button.setBorder(null);
        Home_Button.addActionListener(this::Home_ButtonActionPerformed);
        topPanel1.add(Home_Button);
        Home_Button.setBounds(200, 10, 80, 40);

        jButton4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jButton4.setText("Library");
        jButton4.setBorder(null);
        topPanel1.add(jButton4);
        jButton4.setBounds(290, 10, 80, 40);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (40).png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.addActionListener(this::jButton5ActionPerformed);
        topPanel1.add(jButton5);
        jButton5.setBounds(1120, 10, 50, 60);

        getContentPane().add(topPanel1);
        topPanel1.setBounds(0, 0, 1290, 70);

        jButton1.setBackground(new java.awt.Color(0, 141, 237));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1);
        jButton1.setBounds(1100, 100, 70, 25);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel2.setText("Account");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 90, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Home_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_ButtonActionPerformed
        // TODO add your handling code here:
         // Open Dashtwo dashboard
    Dashtwo dashboard = new Dashtwo();
    dashboard.setVisible(true);

    // Close the current UserBasedFlashcardOwnership window
    this.dispose();
    }//GEN-LAST:event_Home_ButtonActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void UserID_Text_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserID_Text_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserID_Text_FieldActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new UserBasedFlashcardOwnership().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home_Button;
    private javax.swing.JTextField UserID_Text_Field;
    private javax.swing.JPanel centerpanel;
    private javax.swing.JTextField email_Text_Field;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField password_Text_Field;
    private javax.swing.JPanel topPanel1;
    // End of variables declaration//GEN-END:variables
}
